<?php
$title='January';
$datenumber='01';
$content='<p>January is the first calendar months we know today. It was named after the God of the beginnings and the transformations, Janus. Januarius in Latin means the month of Janus. It was added in the <strong>January printable calendar</strong> in 719 BC with 29 days when the king Noma Pompilius was taken on the lunar calendar. This month is dedicated to the Holy Name of Jesus, celebrated on the 3<sup>rd</sup> of January. The initial eight days of January take place amid the liturgical season called Christmas, represented by the white liturgical color. The remaining days of January mark the beginning of the normal time. The liturgical color becomes green, a symbol of hope to reap the eternal heaven harvest, especially the glorious hope.</p>
<p>The name, given to January is obtained from the ancient Roman name Janus who supervised at the New Year\'s Gate. He was celebrated as the God of doorways, gateways and the God of the journey. Janus protected gate of heaven and was linked with the Goddess Juno Janus, often symbolized by the images of a face looking at the same time. This symbolism can easily be related to the month known to many as the beginning of a new year that offers new opportunities. We take the old one and welcome the new one. It is a time when many reflect on the events of the previous year and often decide to repair or improve certain aspects of daily life or personal philosophy. It is better to keep a <strong>January '.$year.' template calendar</strong> and mark the days.</p>
<h2><strong>January Holidays and Events Mentioned in the January Printable Calendar</strong></h2>
<p>Here is a list of some special events marked on the <strong>blank January Calendar </strong>makes a<strong> January printable calendar </strong>and <strong>January template calendar</strong> extremely important.</p>
<h3><strong>New Year&rsquo;s Day</strong></h3>
<p>New Year&rsquo;s Day is celebrated on the 1<sup>st</sup> of January. The beginning of the New Year, at midnight, is announced by fireworks, concerts and special events often broadcast on television. For many, it\'s a day to restore the New Year\'s celebrations the night before. In some cities, parades and private football are organized. The birth of the first New Year\'s baby is often celebrated with gifts to his parents and appearances in local newspapers and local news. New Year&rsquo;s resolutions are taken. New Year\'s resolutions include quitting or drinking alcohol, losing weight, exercising, or adopting a healthier lifestyle.</p>
<h3><strong>Martin Luther King\'s Day </strong></h3>
<p><a href="/when-is/martin-luther-king-day"><span style="text-decoration: underline;">Martin Luther King\'s Day</span></a> is a federal holiday celebrated on the third Monday of January. It is an important day to mark in your <strong>January '.$year.' printable calendar</strong>. Martin Luther King&rsquo;s Day is a holiday. It is a holiday and most schools and businesses are closed. People celebrate the life and achievements of Martin Luther King, an influential American civil rights leader. He is best known for his campaigns to end racial discrimination in public transit and racial equality in the United States. Martin Luther King was a prominent civil rights activist. He was a leader of the End Racism movement in the United States. King\'s Day Martin Luther is considered a relatively new federal day and there are few ancient traditions. This day is considered a day to promote equal rights for all Americans, regardless of their origin. Nowadays, some educational institutions celebrate teaching their students the work of Martin Luther King and his fight against racial discrimination and racism. Martin Luther King Day, also known as the Birthday of Martin Luther King and Martin Luther King is also combined with other days in different states.</p>
<h3><strong>Orthodox Christmas Day</strong></h3>
<p>In the United States, many Orthodox Christians celebrate Christmas Day on or about January 7th of the Gregorian calendar. This date runs on December 25th of the Julian calendar, which precedes the Gregorian calendar. Orthodox Christmas Day is not a holiday. Many Orthodox Christians in countries such as the United States fast before Christmas. Many people recognize fasting as the time to celebrate the birth of Jesus Christ. Fasting is thought to help people focus more on others, spend less time worrying about food, and use more time for praying and helping the poor. By contrast, fasting in British Columbia allows you to fully enjoy the birth, appreciation, and celebration of Christ. Many Orthodox Christians attend a special liturgy in churches on Christmas Day on January 7th. Orthodox churches celebrate Christmas Day with different traditions.</p>
<h3><strong>Confederate Memorial Day</strong></h3>
<p>It is an important day to mark in <strong>January '.$year.' template calendar</strong> as is a holiday in some US states. This gives people the opportunity to honor and remember Confederate soldiers who died or injured during the American Civil War in the 1860s. It is estimated that more than 600,000 soldiers died during the American Civil War and about 260,000 of them were Confederates. In addition, an unknown number of civilians were killed in hostilities. Confederate Memorial Day is observed as a public holiday in some areas where most of the schools are closed. In other regions, Confederate Memorial Day is a normal day of work. Various events are organized in and around this day. University of Georgia main library celebrates this occasion by the display of original Constitution of the Confederate States of America publically. Other celebrations include a ceremony of laying flags and wreaths on the graves and memorials of Confederate soldiers, religious services and remnants of the Civil War. However, this type of celebration is controversial because some see it as a glorification of culture and a way of life that is only carried by slaves.</p>
<h2><strong>January in History</strong><strong>&nbsp;</strong></h2>
<ul>
<li>On January 31, 1747, the first specialized venereal disease clinic opens at London Duke Hospital.</li>
<li>On January 16, 1883, The United States Public Service was founded.</li>
<li>On January 12, 1970, first Boeing 747 Jumbo arrives at Heathrow Airport in London after making its first long-haul flight from New York.</li>
<li>On January 22, 1973, Vietnam Peace Agreement signed between the United States, North and South Vietnam, and Vietcong.</li>
<li>On January 10, 1918, the House of Lords approved the Representation of the People Bill, which gives women over the age of 30 the right to vote.</li>
</ul>
<p>January&nbsp;is the 1<sup>st</sup> month of the year and the beginning of a new resolution. Hence, it is better to have a <strong>January template calendar</strong> or a <strong>'.$year.' January printable calendar</strong> to mark the important events.</p> 
';
