<?php
$day="April Fool's Day";
$content='<h2><strong>April Fool&rsquo;s Day </strong></h2>
<p>April Fools\' Day or sometimes called All Fools\' Day is celebrated every year on April 1 in many parts of the world including US, England, Scotland, Holland, Belgium, Canada, Switzerland, Turkey and Japan. In general, it has become a tradition that people joke to each other on April Fool&rsquo;s Day. Although its origins are uncertain, there are legends about the April Fools\' Day in different cultures, beliefs and languages.</p>
<p>The first day of April is considered the day when he played &ldquo;harmless&rdquo; jokes with friends all over the world. The important word here is &ldquo;harmless&rdquo;, because April Fools\' Day is celebrated as a day for good-natured entertainment.</p>
<p><strong>&nbsp;</strong></p>
<h2><strong>April Fool&rsquo;s Day Background</strong></h2>
<p>It is celebrated in France with the name Poisson d\'avril. In 1582, <a href="https://en.wikipedia.org/wiki/Pope_Gregory_XIII" rel="nofollow noreferrer">Pope Gregory XIII</a> ordered a new calendar (the Gregorian Calendar) to replace the old Julian Calendar. New Year\'s Day of the new calendar is celebrated on January 1st. France adopted the reformed calendar that year and shifted the New Year to January 1. According to a popular statement, many people either refused to accept the new date or did not learn it and continued to celebrate New Year\'s Day on April 1st. Other people began to make fun of these traditionalists and tried to trick them and to send them on a \'fool\'s errand\'. Eventually, the practice spread to Europe.</p>
<p>&nbsp;</p>
<p>Another legend about April Fool&rsquo;s Day is a holiday called Fous holiday in Pagan culture, celebrated on April 1. In ancient Rome, a feast similar to the name of Hilaria is celebrated on the first day of April. In India, this festival is celebrated on March 31 with the name of Holi.</p>
<p><strong>&nbsp;</strong></p>
<p>There are also people who think that April Fool\'s Day is associated with vernal equinox coinciding with the beginning of spring in the Northern Hemisphere. Those who have this belief say that Mother Nature suddenly tricked people by changing the weather.</p>
<p>&nbsp;</p>
<h2><strong>April Fool&rsquo;s Day Celebrations </strong></h2>
<p>April Fool\'s Day is a very special day encourages fun and laughter which reduces stress, although some people claims that it can also have negative consequences, like confusion, worry or wasting time. This entertaining day, which requires being &ldquo;awake&rdquo;, entertains those who joke, as well as those who is joked. Although no one likes to be joked, laughter in the end are very worthy and get a beautiful place in the memories.</p>
<p>For a simple and easy prank, you may use the objects in the house. If you have a bar of soap and some clear nail polish, it means you\'ve got an April Fool\'s Day prank. To do this prank, coat the bar of soap in the clear nail polish and allow it to dry. When someone goes to wash their hands, they will be quite surprising to find that the soap isn\'t working.</p>
<p>&nbsp;</p>
<p>A simple trick you can play with family members or roommates is to remove the batteries from the remote control. When they try to turn on the television, nothing will happen and they will wonder what\'s going on. For extra fun, you can try replacing the batteries with something stupid like baby carrots or leave a note that says &ldquo;April Fools&rdquo;.</p>
<p>&nbsp;</p>
<h2><strong>April Fool&rsquo;s Day Customs and Traditions</strong></h2>
<p>A popular joke of April Fool&rsquo;s Day is to send someone on a \'fool\'s errand\'. In this joke, the victim is sent to someone to deliver a letter asking for help. When a person receives the letter, he or she reads it and tells him to take it to another person. This continues and the victim sends the message to several people until someone is upset about him or her and shows what the letter says: \'Send the fool to others.\'</p>
<p>In the France, Belgium, the Netherlands, Italy, Canada and French-speaking areas of Switzerland, the April 1 tradition is known as \'April Fish\'. A common joke is to try to glue a paper fish to the victim\'s back without being noticed.</p>
<p>In Greece, when someone is the victim of a good joke, they believe that luck will increase, regardless of the misfortune they experience. Therefore, the Greeks typically think of a good joke.</p>
<p>On the April Fool&rsquo;s Day, some newspapers, TV channels and well-known companies also publish false news or announcements to fool people on 1 April.</p>
<p>In Scotland, April Fools\' Day is called Gowkie Day, a common symbol of the fool ("gowk" is another name for the cuckoo). Jokes continue on April 2nd called Taily Day and people traditionally add a "kick me" sign on their friends\' back.</p>
<p><strong>&nbsp;</strong></p>
<h2><strong>April Fool&rsquo;s Day Facts</strong><strong>&nbsp;</strong></h2>
<ul>
<li>Harvesting Spaghetti in Switzerland - 1957: BBC\'s news program Panorama announces on 1<sup>st</sup> of April in 1957 that farmers in Switzerland have made a fertile harvest in winter, thanks to the warm winter and the destruction of wheat lice that have been hauling spaghetti trees. The report contained images of farmers gathering spaghetti hanging from trees. Many viewers called the BBC and asked where they could get the spaghetti tree. The BBC continued the joke and told its viewers to put a spaghetti in a jar of tomato paste and wait for it to grow.</li>
<li>Burgers for left-handers - 1998: Burger King announces a full-page announcement to the USA Today newspaper on the first day of the April in 1998 that they are making hamburgers for 32 million left-handers in the US. According to the announcement, the hamburger was made from the same ingredients as the normal Whopper. However, all materials were turned 180 degrees to the left for left-handed customers. Thousands of left-handed Americans who saw the ad ran to Burger King restaurants to eat the hamburgers produced for them. Right-handed people believe in the joke and wanted to make a special burger for themselves.</li>
<li>Gravity is decreasing - 1976: British astronomer Patrick Moore told BBC that on April 1, at 9.47am Pluto would pass behind Jupiter, which would temporarily reduce gravity on Earth. Moore said those who jumped into the air at the moment of planet alignment would feel as if they were floating in the air. Hundreds of people looking for the BBC after 9.47, said they jumped in the air and felt as if they were swimming in the air. One woman even claimed that they and 11 of her friends took off from their seats and flew around the room.</li>
<li>Loch Ness Monster, found dead - 1972: Newspapers all over the world wrote that the body of Scotland\'s famous Loch Ness Monster was found. Officials at the Flamingo Zoo in Yorkshire announced that the monster\'s body was found swimming in the water. The monster, weighing a ton, was about 5 meters long. Officials said they tried to load the body into their vehicles and bring them to the zoo, but police stopped them under the law, which forbids the removal of unidentified creatures from Loch Ness. The body was taken to the forensic medicine by the police and it turned out to be a huge elephant. The next day, John Shields, one of the people in charge of Flamingo Park, confessed to leaving the body to the lake as a joke on April 1st.</li>
<li>Attention to bomb! - 1915: In the middle of World War I, on the morning of April 1, 1915, a French aviator flew over the German camp and left something similar to a bomb. German soldiers began to escape in panic. When the explosion did not sound, the soldiers searched the place where the bomb fell and found a soccer ball with "April 1" on it.</li>
<li>London Clock Tower to be digital - 2007: The BBC has announced on April 1<sup>st</sup> in 2007 that a digital display will be installed in the London Clock Tower based on technology advances. Thousands of people who opposed the digital display called the BBC. The BBC\'s Japanese service announced that the hour and minute hand in the clock tower will be presented to the first four callers. A Japanese fisherman in the middle of the Atlantic was the first of hundreds to call for having the hour and minute hand.</li>
<li>Spring cleaning on the Internet - 1997: Hundreds of thousands of e-mails across the world have received messages that the Internet will be shut down from March 31 to April 2 for 24-hour spring cleaning. The Internet was to be cleaned by five extremely powerful Japanese-made crawling robots (Toshiba ML-2274). This joke was made for the phone system before.</li>
<li>Socrates\' tomb found - 1995: Greek Ministry of Culture announced that the tomb of Socrates was found during the excavations of the Athens metro system. In the grave was a vase carrying the remains of the hemlock that Socrates drank. French news agency AFP passed the news to all its subscribers. A few hours later, upon the emergence of the joke, AFP withdrew the news.</li>
</ul>
<p>&nbsp;</p>
<h2><strong>April Fool&rsquo;s Day Symbols</strong></h2>
<ul>
<li>Sending someone on a "fool\'s errand"</li>
<li>Trying to get people to believe ridiculous things</li>
<li>Taping a picture of a fish on the back of the schoolmates, crying "Poisson d\'Avril" when the prank is discovered</li>
<li>Publishing fake news</li>
<li>Laughter, laughter and laughter&hellip;</li>
</ul>';
?>
