<?php
$day="Armed Forces Day";
$content='<h2><strong>Armed Forces Day</strong></h2>
<p><span style="text-decoration: underline;">Armed Forces Day</span> is a day to commemorate the people who serve the United States Armed Forces. The day is celebrated each year on the third Saturday in May and every year a theme is designated to the celebration. The first Armed Forces Day was celebrated on Saturday, May 20, 1950. The theme for that day was &ldquo;Teamed for Defense&rdquo;. 2019 theme of the Armed Forces Day was "For the Nation. For the People." 2020 theme has not been decided yet.&nbsp;</p>
<p>&nbsp;</p>
<p>Armed Forces Day is actually a part of Armed Forces Week which is a special week of events and activities are organized over the country, where the citizens can show their appreciations and supports of the Armed Forces community. President Harry S. Truman was instrumental in establishing this American holiday as an important way to thank the military and their families for their service.</p>
<p>Although Armed Forces Day was created to replace the days already celebrated by the Army, Navy, Air Force, Coast Guard, and the Marine Corp, those branches of the military still observe their own specific days in addition to Armed Forces Day.</p>
<p>&nbsp;</p>
<h2><strong>Armed Forces Day Background</strong></h2>
<p>Armed Forces Day was officially created and declared on August 31st, 1949 by the then U.S. Secretary of Defense, Louis Johnson. Each of the other branches of the armed services had their own days until that day. This unification of all of the armed forces&rsquo; holidays reflected the fact that these departments were placed under the Department of Defense. While all of the other branches still recognize their own individual holidays, they also recognize Armed Forces Day. On May 20th, 1950, the newly created Armed Forces Day was celebrated for the first time. Over the years, this holiday has not only been a day to acknowledge people who serve in the armed forces and thank them for their sacrificing service, but it has also been a day when the armed forces have shown off their best military equipment for the American public.</p>
<p>&nbsp;</p>
<p>In 1950, the first Armed Forces Day was celebrated with the theme &ldquo;Teamed Up For Defense&rdquo;, referring that all of the branches of the military had recently been placed under the banner of the Department Of Defense. Since that initial celebration, Armed Forces Day has had a different theme each year. Some of the themes that have been used include: Appreciation of a Nation, Prepared to Meet the Challenge and Freedom Through Unity.</p>
<p>&nbsp;</p>
<h2><strong>Armed Forces Day Celebrations </strong></h2>
<p>There are various ways to observe National Armed Forces Day:</p>
<p>&nbsp;</p>
<ul>
<li>You can participate a parade: National Armed Forces Day is traditionally celebrated with parades honoring military service. Open houses, air shows, and other local celebrations usually accompany a parade. There are numerous local parades across the United States; it is sure to find one of them near you. As Armed Forces Day is about honoring current military personnel, encourage everyone who is participating in the parade to stop and tell what they love most about their freedom and about the American men and women who are fighting for it. Encourage them to share a short story of themselves or a loved one who was in the military.</li>
<li>You can visit a public military display: Military or government personnel generally set up historical or educational displays for the public. Visiting a showcase like this can be eye opening as well as fun. This also gives civilians an opportunity to interact with military personnel face to face.</li>
<li>You can visit a military memorial or cemetery: There are often special ceremonies at military memorials or cemeteries on <a href="https://en.wikipedia.org/wiki/Armed_Forces_Day" target="_blank" rel="nofollow noopener">National Armed Forces Day</a>. Buglers perform the memorial song &ldquo;Taps&rdquo; in honor of fallen soldiers. This is a great way to show your respect and appreciation for members of the military.</li>
</ul>
<p><strong>&nbsp;</strong></p>
<h2><strong>Armed Forces Day Customs and Traditions</strong></h2>
<p><strong>Armed Forces Day</strong> is celebrated in various ways in the United States. In some areas, there are military parades or Armed Forces themed motorcycle tours. There are also many ceremonies, commemorations and music processions organized all over the country. Air shows with military jets and historic military aircraft can be seen in other parts of the country. People can choose to help the family of a deployed soldier. They can offer help with a chore, such as mowing the garden or taking children from school. Even the elimination of a hot meal or even a gift card is a good move and can help ease the burden. Wearing an American flag pin is another idea to observe the Armed Forces Day in your home or office.</p>
<p><strong>&nbsp;</strong></p>
<h2><strong>Armed Forces Day Facts</strong></h2>
<ul>
<li>The army changed from green to blue: Current army troops wear blue instead of green as a tribute to George Washington and the men in his first command.</li>
<li>The Marine Corps wanted their uniforms to be unique: The Marine Corps went to the extent of including the letters &ldquo;USMC&rdquo; when designing their uniforms so that other branches wouldn&rsquo;t be able to use their design.</li>
<li>Stripes on Navy uniforms were a fashion choice: It turns out there&rsquo;s no significance to the three pin-stripes on the Navy jumper other than the fact that a majority of the men were decorating their collars with various types of white stripes &mdash; so it became part of the uniform.</li>
<li>Sailors wear bell-bottoms for a reason: The wide-bottomed pants that sailors famously wear are constructed that way so that they can easily be folded up when performing duties that involve them getting their feet wet.</li>
<li>The flag patch is backwards on purpose: The American flag patch on military uniforms has the stars on the right and stripes on the left in order to give the effect that it\'s blowing in the breeze.</li>
<li>On Armed Forces Day military exercises are held at sea, in the air, and on land as a means to honor their members and to show the U.S. civilian population their state-of-the-art equipment.</li>
<li>Armed Forces Day is not a federal holiday.</li>
<li>The Armed Forces Day Parade in Bremerton, Washington is the longest running city sponsored parade of its kind. In 2015 it will be the parade\'s 67th anniversary.</li>
<li>The parade held in New York City on the first Armed Forces Day had more than 36,000 participants.</li>
<li>On the first Armed Forces Day B-36 bombers flew over every U.S. capital.</li>
<li>On the first Armed Forces Day there was a march in Washington, D.C. with more than 10,000 veterans and troops.</li>
<li>President John F. Kennedy issued Proclamation 3399 on March 18th, 1961 making Armed Forces an official national holiday.</li>
<li>It is tradition to fly the American flag on Armed Forces Day. It is also common to see people wearing patriotic colored clothing on Armed Forces Day.</li>
<li>The U.S. Department of Defense is the largest employer in America with approximately 2.3 million serving and 1.8 on active duty. Due to retirement or completed service the armed forces must recruit approximately 165,000 people each year.</li>
<li>Other countries that celebrate an all-in-one Armed Forces Day include Armenia, Australia and New Zealand, Azerbaijan, Bangladesh, Bulgaria, Burma, Canada, Chile, China, Cuba, Egypt, Finland, France, Georgia, Guatemala, Hungary, Indonesia, Iran, Iraq, Japan, Lebanon, Mali, Malaysia, Mauritania, Mexico, North Korea, Philippines, Poland, Romania, Russia, Singapore, South Korea, Spain, Thailand, Ukraine, the United Kingdom, Venezuela, and Vietnam.</li>
</ul>
<p>&nbsp;</p>
<h2><strong>Armed Forces Day Symbols</strong></h2>
<p>You can start the day by finding volunteers to help decorate them by placing red, white and blue balloons in your home or garden. Balloons are the easiest and cheapest way to decorate, and having classic red, white and blue balloons throughout will create an instant and festive atmosphere. If you\'re looking for exterior decoration, place patriotic windmills or American flags in the ground in your home\'s garage to appeal to the curb. Don\'t forget to keep your exterior decorations for Memorial Day. If you need more decorations, you can prepare for this important day by making handcrafted ornaments and designs a few days in advance. Once your decorations are complete, it&rsquo;s time to focus on getting your residents and neighbors into the patriotic spirit. Encourage all the family members and friends to wear their red, white, and blue clothes or accessorizes for the day. Moreover, you may consider hosting a fun red, white, and blue fashion show to award the resident who can put together the most patriotic attire. Another idea can be using the morning of Armed Forces Day as a time for your facility&rsquo;s clubs to participate in patriotic activities, like encouraging your Baking Club to make tasty red, white, and blue cookies or inviting the Crafts Club to use patriotic beads to make necklaces for residents to wear for the day.</p>
<p>Finally, don&rsquo;t forget about the kids on this special day. Saturday is the most visited day for most nursing facilities, and that also includes visits from children. To get the grandchildren in on the celebration, set up a special table for them to use to write letters and to color pictures that can be mailed to troops overseas. You may also reward the kids for their participation by supplying them with patriotic favors like patriotic pencils or special mints.</p>';
?>
