<?php
$day="Black Friday";
$content='<h2><strong>Black Friday</strong></h2>
<p>The day after <a href="/when-is/thanksgiving">Thanksgiving Day</a> that signals the beginning of the Christmas shopping season. Black Friday is one of the biggest shopping days of the year. Retailers kick off the season by offering deep discounts on products for those shoppers lucky enough to obtain the limited supply. Brick and mortar stores traditionally open much earlier than normal business hours, including a few at 12:00 AM midnight. In recent years, e-commerce sites have begun offering discounts and free shipping on Black Friday, as well as created their own shopping holiday in Cyber Monday.</p>
<h2><strong>Black Friday Background</strong></h2>
<p>The day after Thanksgiving wasn\'t called Black Friday then. The name was associated with September 24, 1869. Two speculators, Jay Gould, and James Fisk created a boom-and-bust in gold prices. A stock market crash followed as prices fell 20%. The disruption in gold prices sent commodity prices plummeting 50%. Corruption in Tammany Hall allowed Gould and Fisk to escape without punishment.</p>
<p>In 1905, Canadian department store Eaton\'s began the first Thanksgiving Day parade by bringing Santa on a wagon through the streets of downtown Toronto. In 1913, eight live reindeer pulled Santa\'s "sleigh." By 1916, seven floats representing nursery rhyme characters joined Santa in the parade. &nbsp;In 1924, the Eaton\'s parade inspired Macy\'s Department Store to launch its famous Thanksgiving Day parade in New York City. Macy\'s wanted to celebrate its success during the Roaring 20s. The parade boosted shopping for the following day. Retailers had a gentleman\'s agreement to wait until then before advertising holiday sales.&nbsp;</p>
<p>In 1939, during the Great Depression, Thanksgiving happened to fall during the fifth week of November. Retailers warned they would go bankrupt because the holiday shopping season was too short. They petitioned President Franklin D. Roosevelt to move the Thanksgiving holiday up to the fourth Thursday. Unfortunately, by this time it was late October. Most people had already made their plans. Some were so upset that they called the holiday "Franksgiving" instead. Only 32 states followed FDR\'s move. Others celebrated two holidays, which forced some companies to give their employees an extra day off.</p>
<p>In 1941, Congress ended the confusion. It passed a law that made Thanksgiving the fourth Thursday in November no matter what. &nbsp;In the 1950s, people began calling in sick the day after Thanksgiving, essentially giving themselves a four-day weekend. Since stores were open, as were most businesses, those playing hooky could also get a head start on their holiday shopping. That&rsquo;s as long as the boss didn\'t see them. Rather than try to determine whose pay should be cut, and who was legitimately sick, many businesses started adding that day as another paid holiday.</p>
<p>In 1966, the Black Friday name became famous in print. That\'s when a story appeared in an ad in The American Philatelist, a stamp collectors\' magazine.&nbsp; The Philadelphia Police Department used the name to describe the traffic jams and crowding in the downtown stores. &nbsp;In 2014, an internet meme created a myth about Black Friday and slaves. It falsely claimed slave traders gave discounts at auctions on the day after Thanksgiving</p>
<h2><strong>Black Friday Celebrations </strong></h2>
<p>Historically, shoppers did half their holiday shopping on Black Friday. The holiday season consists of November and December, according to the National Retail Federation(NRF). In 2008, holiday sales fell 4.6% from the prior year. That\'s the first time sales dropped since the NRF began tracking in 1992. Sales typically rose 3.4% each year.&nbsp;</p>
<p>In 2009, sales increased by 0.3%. Shoppers spent $373 each on Black Friday. That\'s more than half of the $673 each spent during the entire 2009 holiday season. Holiday sales rebounded 5.2% in 2010, once the recession was safely over. Black Friday weekend sales were $45 billion.</p>
<p>In 2011, many stores opened on Thanksgiving evening for the first time. Those sales were included in Black Friday sales. They were $12.3 billion, up 2.3% from 2010. Overall holiday sales rose 4.6%.&nbsp; In 2013, combined online and store sales for the entire Black Friday weekend were $57.4 million. It was lower than the $60 million spent in 2012. Many shoppers took advantage of online sales that began in early November. Others waited for bigger discounts later in the shopping season. The NRF stopped giving sales estimates for Black Friday in 2013. Instead, it reported on sales for the holiday season.<strong>&nbsp;</strong></p>
<h2><strong>Black Friday Customs and Traditions</strong></h2>
<p>Black Friday is the Friday immediately after Thanksgiving when retailers begin the holiday shopping season. It&rsquo;s based around the aforementioned &ldquo;doorbusters&rdquo;, discounts so impressive that bargain-crazed customers will try to break the doors down before the shop opens - although that&rsquo;s more of a virtual craze these days.&nbsp; The actual date shifts every year, by the day of the week stays the same: it\'s always the Friday after Thanksgiving, and this year it\'s later in the month of November. The official Black Friday date is November 29, 2019, and November 27, 2020 meaning it\'s closer to Christmas (less than a month before Christmas Day), and that gives you less time to shop online.<strong>&nbsp;</strong></p>
<h2><strong>Black Friday Facts</strong></h2>
<ul>
<li>It&rsquo;s not the busiest shopping day of the year. The Saturday before Christmas is!</li>
<li>According to a 2009 article published in TIME magazine, the phrase &ldquo;Black Friday&rdquo; was first used in the 1960s by Philadelphia newspapers referring to the huge rush of crowds to stores on the day after Thanksgiving.</li>
<li>The current &ldquo;Black Friday&rdquo; term first became used widely in the 1990&rsquo;s and refers to retailers reaching profitability or in the black &ndash; black ink, as opposed to losses which were originally recorded in red ink.</li>
<li>Not all the best deals are offered on Black Friday:
<ul>
<li>Most deals for electronics are offered at the beginning of November.</li>
<li>The best day to save on Christmas decor is November 22. Discounts are 23 percent on average.</li>
<li>The best day to buy toys is the day before Thanksgiving.</li>
<li>Many online sales discounts are better on Thanksgiving Day for items such as sporting goods and apparel. The average discount is 24 percent.</li>
<li>If you dare to wait, the last few days of the shopping season often advertise products 10 to 15 percent cheaper than on Black Friday.</li>
</ul>
</li>
<li>Black Friday is still the best day for deals on TVs, tablets, appliances and jewelry.</li>
<li>The days from Thanksgiving through Cyber Monday capture 20 percent of all holiday online shopping.</li>
<li>For 2017, Amazon and Walmart are expected to dominate online sales. While the No. 3 spot is still up for grabs between Best Buy and Target.</li>
<li>On average, shoppers will wait 2.5 hours in line for a deal.</li>
<li>The average shopper spent over $900 in 2016 on Black Friday and expected to spend nearly $1,000 this year.</li>
<li>Black Friday sales declined only once in recent years. It was 2008 during the Great Recession. Only 263,820 seasonal workers were hired in 2008 &ndash; staggering low compared to the record 764,750 workers hired in 2013.</li>
<li>"Black Friday" used to refer to stock market crashes in the 1800s. Although it is now known as the biggest shopping day in the US, the term "Black Friday" originally referred to very different events. "Black for centuries has been used for various calamities," says linguist Benjamin Zimmer, executive editor of Vocabulary.com.</li>
<li>"Santa Claus parades" were Black Friday\'s predecessor. For many Americans, the Macy\'s Thanksgiving Day Parade has become part of the holiday ritual. But the event actually was inspired from the US\'s neighbors in the north. Canadian department store Eaton\'s held the first "Santa Claus parade" on 2 December 1905. Once Santa appeared at the end of the parade, the signal was that the holiday season - and thus, holiday shopping, had begun. Of course, consumers were encouraged to buy their presents at Eaton\'s. US department stores such as Macy\'s took inspiration from the parade, and started sponsoring similar efforts across the country.</li>
<li>Black Friday became the biggest shopping day of the year in 2001. Although it\'s often touted as the biggest shopping day of the year, the day didn\'t earn the designation consistently until the 2000s. That\'s because, for many years, the rule wasn\'t that Americans loved deals, it was that they loved procrastinating. So up until that point, it was the Saturday before Christmas that typically saw the most wallets being emptied.</li>
</ul>
<h2><strong>Black Friday Symbols</strong></h2>
<p>The city that first popularized the term was Philadelphia. Police officers, frustrated by the congestion caused by shoppers on the day, started referring to it derisively as "Black Friday". Unsurprisingly, retailers weren\'t happy to be associated with traffic and smog. They tried to rebrand the day "Big Friday", according to a 1961 local Philadelphia paper. The phrase \'Black Friday\' remained a Philadelphia quirk for a surprisingly long time. "You see it spreading a little bit to Trenton, New Jersey, which is close by, but it doesn\'t really start getting mentioned outside of Philadelphia until the 1980s," says Mr. Zimmer. "It didn\'t become widespread until the mid-90s." Retailers tried to put a positive spin on the "black" bit of the term by saying it was when retailers became profitable, or as the saying goes "went into the black". However, there is no evidence to back this claim up. It is true that holiday sales make up the bulk of consumer spending for the year.</p>';
?>
