<?php
$day="Christmas Day";
$content='<h2><strong>Christmas Day</strong></h2>
<p>Christmas is one of the most important as well as popular festivals celebrated in more than 160 countries throughout the world.&nbsp; Christmas is a celebration of the birth of Jesus Christ, who in the Christian religion, is also known as \'The Son Of God\'.&nbsp; Christmas is celebrated by those following the religion of Christianity, though the festival has universal appeal, across all religions. There are many ways to celebrate Christmas even though the Christmas spirit is universal in nature. Essentially, there are three different days in which one can celebrate the holiday. The first day of celebration is the day before Christmas, which is known as <a href="https://en.wikipedia.org/wiki/Christmas_Eve" >Christmas Eve</a>. It is celebrated on December 24, every year, according to the Gregorian calendar. The second day is Christmas Day, which is celebrated on December 25 every year. The third day is known as Boxing Day, celebrated the day after Christmas, on December 26.</p>
<h2><strong>Christmas Day Background</strong></h2>
<p>The early Christian community distinguished between the identification of the date of Jesus&rsquo; birth and the liturgical celebration of that event. The actual observance of the day of Jesus&rsquo; birth was long in coming. In particular, during the first two centuries of Christianity there was strong opposition to recognizing birthdays of martyrs or, for that matter, of Jesus. Numerous Church Fathers offered sarcastic comments about the pagan custom of celebrating birthdays when, in fact, saints and martyrs should be honoured on the days of their martyrdom&mdash;their true &ldquo;birthdays,&rdquo; from the church&rsquo;s perspective.</p>
<p>The precise origin of assigning December 25 as the birth date of Jesus is unclear. The New Testament provides no clues in this regard. December 25 was first identified as the date of Jesus&rsquo; birth by Sextus Julius Africanus in 221 and later became the universally accepted date. One widespread explanation of the origin of this date is that December 25 was the Christianizing of the dies solis invicti nati (&ldquo;day of the birth of the unconquered sun&rdquo;), a popular holiday in the Roman Empire that celebrated the winter solstice as a symbol of the resurgence of the sun, the casting away of winter and the heralding of the rebirth of spring and summer.<strong>&nbsp;</strong></p>
<h2><strong>Christmas Day Celebrations </strong></h2>
<p>A very early Christian tradition said that the day when Mary was told that she would have a very special baby, Jesus (called the Annunciation) was on March 25th - and it\'s still celebrated today on the 25th March. Nine months after the 25th March is the 25th December! March 25th was also the day some early Christians thought the world had been made, and also the day that Jesus died on when he was an adult. The date of March 25th was chosen because people had calculated that was the day on which Jesus died as an adult and they thought that Jesus was born and had died on the same day of the year. Some people also think that December 25th might have also been chosen because the Winter Solstice and the ancient pagan Roman midwinter festivals called \'Saturnalia\' and \'Dies Natalis Solis Invicti\' took place in December around this date - so it was a time when people already celebrated things.</p>
<h2><strong>Christmas Day Customs and Traditions</strong></h2>
<p>For two millennia, people around the world have been observing it with traditions and practices that are both religious and secular in nature. Christians celebrate Christmas Day as the anniversary of the birth of Jesus of Nazareth, a spiritual leader whose teachings form the basis of their religion. Popular customs include exchanging gifts, decorating Christmas trees, attending church, sharing meals with family and friends and, of course, waiting for Santa Claus to arrive. December 25&ndash;Christmas Day&ndash;has been a federal holiday in the United States since 1870.</p>
<h2>&nbsp;<strong>Christmas Day Facts</strong></h2>
<ul>
<li>Christmas is celebrated on the 25th of December, which marks the birth of Jesus Christ. However, the exact date and month of Jesus&rsquo; birth are unknown.</li>
<li>Even though the majority of the population believes that Jesus was born on this day, they spend more time visiting shopping malls than studying the life of the messenger.</li>
<li>The Statue of Liberty was gifted to the US by the French on Christmas day in 1886. It weighs 225 tons and thus you could consider it as the biggest Christmas gift in the world.</li>
<li>Other names of Christmas from the old times include &ndash; &lsquo;Midwinter&rsquo;, &lsquo;Nativity&rsquo; and &lsquo;Yule&rsquo;.</li>
<li>More than 3 billion Christmas cards are sent in the U.S. alone, every year. The business of &lsquo;Christmas cards&rsquo; is huge, if you are looking for one.</li>
<li>The other name of &lsquo;Christmas Tree&rsquo; is Yule-tree.</li>
<li>Hallmark introduced their first Christmas cards in 1915.</li>
<li>Between the 16th and 19th centuries global temperatures were significantly lower than normal in what was known as a &ldquo;little ice age&rdquo;. Charles Dickens grew up during this period and experienced snow for his first eight Christmases. This &ldquo;White Christmas&rdquo; experience influenced his writing and began a tradition of expectation for the holidays.</li>
<li>The Christmas tree in Trafalgar Square is donated to the people of London every year by the people of Oslo, Norway in thanks for their assistance during World War II.</li>
<li>Since 1918 the city of Boston has received a giant Christmas tree as a gift from the Canadian province of Nova Scotia. Boston lent considerable support to the city of Halifax during their 1917 explosion and subsequent fire disaster.</li>
<li>In 1914 during World War I there was a now famous Christmas truce in the trenches between the British and the Germans. They exchanged gifts across a neutral no man&rsquo;s land, played football together, and decorated their shelters.</li>
<li>In 2010 during the Christmas season, the Colombian government decorated jungle trees with lights. The trees lit up when the guerrillas (terrorists) walked by and banners appeared asking them to surrender their arms. The campaign convinced 331 guerillas to re-enter society and also won an award for strategic marketing excellence.</li>
<li>Bicycle, the U.S. playing card company, manufactured cards to give all the POWS in Germany during World War II as Christmas presents. These cards, when soaked in water, revealed an escape route for POWs. The Nazis never knew.</li>
<li>The Christmas wreath was originally hung as a symbol of Jesus. The holly represents his crown of thorns and the red berries the blood he shed.</li>
<li>The three traditional colors of most Christmas decorations are red, green and gold. Red symbolizes the blood of Christ, green symbolized life and rebirth, and gold represents light, royalty and wealth.</li>
<li>In Poland spiders are considered to be symbols of prosperity and goodness at Christmas. In fact, spiders and spider webs are often used as Christmas tree decorations. According to legend, a spider wove baby Jesus a blanket to keep him warm.</li>
<li>Brenda Lee recorded &ldquo;Rockin&rsquo; Around the Christmas Tree&rdquo; when she was only 13 years old.</li>
<li>Famous saxophonist Boots Randolph played the saxophone solo on &ldquo;Rockin&rsquo; Around the Christmas Tree&rdquo;.</li>
<li>Paul McCartney&rsquo;s Christmas song is widely regarded as the worst of all the songs he ever recorded yet he earns $400,000 a year off of it.</li>
<li>If you gave all the gifts listed in the Twelve Days of Christmas, it would equal 364 gifts.</li>
<li>In Dublin in 1742 the Christmas oratorio, &ldquo;The Messiah&rdquo;, by George Frederick Handle was first performed.</li>
<li>NORAD&rsquo;s &ldquo;Santa Tracker&rdquo; was born from a misprint in the newspaper. A 1955 Sears ad was supposed to print the number of a store where children could call and tell Santa what they wanted for Christmas. The number printed was to the hotline of the Director of Operations for the U.S. Continental Air Defense. Colonel Shoup ordered his staff to give the children updates on the flight coordinates of Santa.</li>
</ul>
<h2><strong>Christmas Day Symbols</strong></h2>
<ul>
<li>The image of Santa Claus flying his sleigh began in 1819 and was created by Washington Irving, the same author who dreamt up the Headless Horseman.</li>
<li>The Montgomery Ward department store created Rudolph the Reindeer as a marketing gimmick to encourage children to buy their Christmas coloring books.</li>
<li>The tradition of hanging stockings comes from a Dutch legend. A poor man had three daughters for whom he could not afford to provide a dowry. St. Nicholas dropped a bag of gold down his chimney and gold coins fell out and into the stockings drying by the fireplace. The daughters now had dowries and could be married, avoiding a life on the streets.</li>
<li>The old English custom of wassailing was to toast to someone&rsquo;s long life at Christmastide and was the forerunner for the tradition of Christmas caroling. In the 13th century St. Francis of Assisi began the custom of singing carols in church.</li>
<li>&lsquo;Jingle Bells&rsquo; &ndash; the popular Christmas song was composed by James Pierpont in Massachusetts, America. It was, however, written for thanksgiving and not Christmas.</li>
<li>&lsquo;Jingle Bells&rsquo; &ndash; was the first song sung by astronauts Tom Stafford and Wally Schirra in space, on December 16, 1965.</li>
<li>Christmas tree decoration is believed to have originated in the 16th century in Germany.</li>
<li>The &lsquo;X&rsquo; in X-Mas, as we all use today, comes from the Greek meaning of &lsquo;X&rsquo; i.e. Christ.</li>
</ul>';
?>
