<?php
$day="Columbus Day";
$content='<h2><strong>Columbus Day</strong></h2>
<p>In the United States, <strong>Columbus Day</strong> is a fall holiday that commemorates Italian explorer Christopher Columbus\'s arrival in the New World on October 12, 1492. It has been a federal holiday since 1937 and is always celebrated on the second Monday in October: New England\'s best month of the year. Though Columbus Day is one of the 10 U.S. legal federal holidays, it is not considered a major one. There will be no postal service. It is a Federal Reserve Bank holiday, so while banks may open, some transactions will not be processed. Most businesses remain open and retail stores may run special sales. The New York Stock Exchange and Nasdaq remain open on this federal holiday. In addition to a state level, in many cities, the day is now celebrated as Native Americans&rsquo; Day or Indigenous People&rsquo;s Day.</p>
<h2><strong>Columbus Day Background</strong></h2>
<p>Christopher Columbus set sail from the port of Palos de la Frontera, Spain, in August 1492 with backing from the Spanish monarchs King Ferdinand and Queen Isabella. His goal: to chart a lucrative western sea route to China, India, and the rumored spice islands of Asia. But instead, on October 12, he landed in the Bahamas&mdash;on the island the indigenous people called Guanahani (which he renamed San Salvador Island.). This feat made him the first European to explore the Americas since the Vikings set up colonies in Greenland and Newfoundland during the 10th century. Columbus also spotted Cuba, which he thought was China, and then in December, he and his crew arrived Hispaniola, an island in the Caribbean, and established Spain&rsquo;s first colony in the Americas. When he returned to Europe he brought spices, gold and &ldquo;Indian&rdquo; captives&mdash;it is reported that he kidnapped six West Indies natives the first day he made landfall and forced them to be his servants. Over the next eight years, Columbus made three more Transatlantic expeditions. On his third voyage in 1498, he realized that he had not reached Asia, but instead had accidentally found a continent whose existence had been erased from the collective memory of most of Europe. Colorado first observed Columbus Day in 1906 as it became an official state holiday.&nbsp; More and more people and states began to recognize Columbus Day.&nbsp; In 1937, Columbus Day became a federal holiday in the United States.&nbsp; There are many instances of people observing Columbus&rsquo; voyage since the colonial period.&nbsp; In 1792, there were celebrations in New York City and other US cities, celebrating the 300th anniversary of his landing in the New World.&nbsp; President Benjamin Harrison called upon the people of the United States to join together in celebration of Columbus Day on the 400th anniversary of the event.&nbsp; During the anniversary in 1892, teachers, preachers, poets and politicians used Columbus Day rituals to teach ideals of patriotism.&nbsp; These patriotic teachings were framed around themes of support for war, citizenship boundaries, the importance of loyalty to the nation and celebrating social progress. In 1970, Columbus Day was changed to the current observation on the second Monday in October.</p>
<p>Columbus Day is celebrated on the second Monday in October, but up until 1970 it was celebrated on October 12 to commemorate Columbus\' arrival in the Americas which occurred on October 12, 1492. Since 1971 due to The Uniform Monday Holiday Act, the holiday\'s date has been fixed to the second Monday in October.</p>
<h2><strong>Columbus Day Celebrations </strong></h2>
<p>Columbus Day first began to be celebrated in some U.S. cities and states as early as the 18th century, but it was named an official federal holiday in 1937. Most banks and courthouses are closed, and though some stores will mark the occasion with promotions like &ldquo;Columbus Day Savings,&rdquo; many other businesses don&rsquo;t bother to call out the day.&nbsp; The largest celebration of Columbus Day is in New York City, which hosts a huge parade. Communities with large Italian American populations may hold special Columbus Day festivities.</p>
<p>The first celebration of Columbus&rsquo;s landing in the New World took place in 1792. It was organized by the Columbian Order (Society of St. Tammany) in New York City. In 1937, the occasion was declared a national holiday by President Franklin D. Roosevelt. Columbus Day has been observed on the second Monday of October since 1971. Many celebrate Italian-American heritage on this day.</p>
<p>The observance of Columbus Day is not without controversy. European exploration brought disease, harsh treatment, and devastation to the lives of the indigenous people of the Americas. Some areas of the United States choose to honor Native American culture on this day instead. Since 1992, this state and city holiday has been referred to as Indigenous Peoples&rsquo; Day.&nbsp;</p>
<h2><strong>Columbus Day Customs and Traditions</strong></h2>
<p><strong>Columbus Day</strong> became a federal holiday in the United States in 1937 due to the decision of Congress and President Franklin Delano Roosevelt. Nowadays it is generally observed by the U.S. Postal Service, federal agencies, banks, most state government offices, most school districts and many businesses. Most states celebrate it as an official state holiday and close schools and other state services.</p>
<p>Columbus Day recognizes the achievements of a great Renaissance explorer who founded the first permanent European settlement in the New World. The arrival of Columbus in 1492 marks the beginning of recorded history in America and opened relations between the Americas and the rest of the world. Columbus Day is one of America&rsquo;s oldest holiday, and is a patriotic holiday. In fact, the Pledge of Allegiance was written in 1892 in honor of the 400th anniversary of his first voyage. That year, President Benjamin Harrison declared Columbus Day a legal holiday.</p>
<h2><strong>Columbus Day Facts</strong></h2>
<ul>
<li>Columbus Day is one of ten federal holidays recognized nationwide by the United States Government.</li>
<li>According to data from the Society for Human Resource Management, only 14% of organizations closed on Columbus Day</li>
<li>Christopher Columbus was born in 1451 in Genoa, Italy. He began sailing when he was only 15 years old.</li>
<li>When he set sail for the expedition, he was given three ships by the city of Palos.</li>
<li>He set sail in August of 1492. It was 35 days before a sailor spotted land.</li>
<li>The names of the three ships were the Nina, the Pinta, and the Santa Maria.</li>
<li>His crew consisted of 90 men.</li>
<li>The goal of the expedition was to chart a western sea route to India and China, as well as to the islands in Asia with spices and gold.</li>
<li>When Christopher Columbus landed in the Bahamas in 1492, he was the first European since the 10th century to have the opportunity to explore the Americas.</li>
<li>The Santa Maria did not make the return trip to Spain because it ran aground on Christmas Day. 40 men had to stay behind because there was no room on the other two ships. They stayed behind on the island Hispaniola.</li>
<li>Christopher Columbus made the voyage to the New World three times.</li>
<li>He died when he was 55, in 1506, only two years after his last trip to the New World.</li>
<li>Nobody is sure where he is buried as he was reburied many times in different places around the world.</li>
<li>Nobody is sure what he looked like, as there are no portraits known to exist.</li>
<li>President Roosevelt made Columbus Day a national holiday in 1934.</li>
<li>In 1971, the date October 12th no longer marked the holiday. It was changed to the second Monday in October. This is also the Canadian Thanksgiving, which was fixed in 1959).</li>
<li>South Dakota, Alaska and Hawaii do not recognize Columbus Day.</li>
<li>In Latin America they call this day D&iacute;a de la Raza; in the Bahamas they call it Discovery Day; in Spain they call it Fiesta Nacional and D&iacute;a de la Hispanidad; in Argentina they call it D&iacute;a del Respeto a la Diversidad Cultural; in Belize they call it Day of the Americas, and in Uruguay they call it Day of the Americas.</li>
<li>In Puerto Rico, Columbus Day is celebrated along with Puerto Rico Friendship Day.</li>
<li>In Virginia, Columbus Day is celebrated along with Yorktown Victory Day.</li>
<li>Because Christopher Columbus was Italian, Italian-Americans celebrate Columbus Day as a celebration of their heritage.</li>
<li>Depending on where you live in the United States, you may see parades to celebrate the holiday. In most states, the children have the day off school.</li>
<li>New York City has the largest parade on Columbus Day.</li>
</ul>
<h2><strong>Columbus Day Symbols</strong></h2>
<p>For much of its history, the United States considered Columbus a man worthy of admiration. Columbus Day is one of America&rsquo;s oldest patriotic holidays, first celebrated in the 18th century. It was first celebrated on October 12, 1792, when the <a href="https://en.wikipedia.org/wiki/Tammany_Hall" target="_blank" rel="noopener nofollow">New York Society of Tammany</a> honored Columbus on the 300th anniversary of his first voyage. America has more monuments to Columbus than any other nation in the world.</p>
<p>Columbus celebrates the beginning of cultural exchange between America and Europe. After Columbus, millions of European immigrants brought their art, music, science, medicine, philosophy and religious principles to America. These contributions have helped shape the United States and include Greek democracy, Roman law, Judeo-Christian ethics and the belief that all men are created equal.</p>';
?>
