<?php
$day="Earth Day";
$content='<h2><strong>Earth Day</strong></h2>
<p><span style="text-decoration: underline;">Earth Day</span> is an annual event created to celebrate the planet\'s environment and raise public awareness about pollution. The day, marked on April 22, is observed worldwide with rallies, conferences, outdoor activities and service projects.</p>
<p>Earth Day was founded in 1970 as a day of education about environmental issues, and Earth Day '.$title_year.' occurs on April 22. The holiday is now a global celebration that&rsquo;s sometimes extended into Earth Week, a full seven days of events focused on green living. The brainchild of Senator Gaylord Nelson and inspired by the protests of the 1960s, Earth Day began as a &ldquo;national teach-in on the environment&rdquo; and was held on April 22 to maximize the number of students that could be reached on university campuses. By raising public awareness of pollution, Nelson hoped to bring environmental causes into the national spotlight.</p>
<p>Everyone can participate in Earth Day. People of all ages can march, plant trees, clean up their communities, and reduce waste in their own homes. Proactive corporations and governments often use Earth Day to announce sustainability measures and pledge to support the environment.</p>
<p>&nbsp;</p>
<h2><strong>Earth Day Background</strong></h2>
<p>Started as a grassroots movement, Earth Day created public support for the creation of the Environmental Protection Agency (EPA) and contributed to the passage of the Clean Air Act, the Water Quality Improvement Act, the Endangered Species Act and several other environmental laws. The idea for Earth Day was proposed by then-Sen. Gaylord Nelson of Wisconsin, who died in 2005.</p>
<p>The first Earth Day was in 1970. Nelson, after seeing the damage done by a 1969 massive oil spill in Santa Barbara, California, was inspired to organize a national "teach-in" that focused on educating the public about the environment. Nelson recruited Denis Hayes, a politically active recent graduate of Stanford University, as national coordinator, and persuaded U.S. Rep. Pete McCloskey of California to be co-chairman. With a staff of 85, they were able to rally 20 million people across the United States on April 20, 1970. Universities held protests, and people gathered in public areas to talk about the environment and find ways to defend the planet.</p>
<p>Though the environmental movement is a relatively recent phenomenon, the consciousness behind it is as old as mankind. These Earth Day quotes from some of the greatest writers and philosophers in history will help to illuminate that past and show the inspiration behind Earth Day.</p>
<p><strong>&nbsp;</strong></p>
<h2><strong>Earth Day Celebrations </strong></h2>
<p>Earth Day continued to grow over the years. In 1990, it went global, and 200 million people in 141 countries participated in the event, according to the Earth Day Network.</p>
<p>&nbsp;</p>
<p>Earth Day 2000 included 5,000 environmental groups and 184 countries. Hayes organized a campaign that focused on global warming and clean energy. "The world\'s leaders in Kyoto, Japan, in late 1997, acknowledged the scientific fact that the leading cause of global warming is carbon emissions from fossil-fuel consumption, and that something must be done to address those rising emissions," Hayes told National Geographic.</p>
<p>&nbsp;</p>
<p>In 2010, for the 40th anniversary of Earth Day, 225,000 people gathered at the National Mall for a climate rally. Earth Day Network launched a campaign to plant 1 billion trees, which was achieved in 2012, according to the organization.</p>
<p><strong>&nbsp;</strong></p>
<p>Since 1970, Earth Day celebrations have grown. In 1990, Earth Day went global, with 200 million people in over 140 nations participating, according to the Earth Day Network (EDN), a nonprofit organization that coordinates Earth Day activities. In 2000, Earth Day focused on clean energy and involved hundreds of millions of people in 184 countries and 5,000 environmental groups, according to EDN. Activities ranged from a traveling, talking drum chain in Gabon, Africa, to a gathering of hundreds of thousands of people at the National Mall in Washington, D.C. Today, the Earth Day Network collaborates with more than 17,000 partners and organizations in 174 countries. According to EDN, more than 1 billion people are involved in Earth Day activities.</p>
<p>&nbsp;</p>
<h2><strong>Earth Day Customs and Traditions</strong></h2>
<p>The April 22 Earth Day is usually celebrated with outdoor performances, where individuals or groups perform acts of service to Earth. Typical ways of observing Earth Day include planting trees, picking up roadside trash, conducting various programs for recycling and conservation, and using recyclable containers for snacks and lunches. Some people are encouraged to sign petitions to governments, calling for stronger or immediate action to stop global warming and to reverse environmental destruction. Television stations frequently air programs dealing with environmental issues.</p>
<p>The theme for Earth Day '.$title_year.' focuses on renewable energy and climate action. Each year, Earth Day organizers announce a global theme that unites supporters across 192 countries in a commitment to protect the planet through smart energy choices and sustainability.</p>
<p>&nbsp;</p>
<p>The Earth Day Network, responsible for running Earth Day, says 40 percent of the world\'s 11,000 bird species are in decline and 75 percent of the world\'s coral reefs are under stress. Earth Day is encouraging its supporters to take individual actions to slow the extinction rate. Easily achievable ideas include going vegetarian or cutting the use of pesticides and herbicides.</p>
<p>&nbsp;</p>
<h2><strong>Earth Day Facts</strong></h2>
<ul>
<li>Earth Day is not the same as Equinox Day. Equinox Day, which also celebrates the idea of caring for the planet, is held on the first day of spring, March 20th.</li>
<li>Earth Day has its own theme song. The Earth Day Anthem was written in 2013 by Indian poet Abhay Kumar, and has since been recorded in all official UN languages.</li>
<li>This global movement has inspired real change. On Earth Day 2011, 28 million trees were planted in Afghanistan for a &ldquo;Plant Trees Not Bombs&rdquo; campaign. In 2012, more than 100 thousand people in China rode their bikes in order to reduce CO2 emissions and highlight the amount of pollution created by cars.</li>
<li>Each year, the Earth Day theme changes. In 1990, the spotlight was on global mobilization of environmental issues with a strong focus on recycling. In 2000 it was about global warming and clean energy. 2010 marked the world&rsquo;s largest environmental service project&mdash;A Billion Acts of Green&mdash;as well as a 250,000-person climate change rally in Washington DC. This year&rsquo;s campaign is to End Plastic Pollution, an effort to eliminate single-use plastics.</li>
<li>According to a survey from device recycler ecoATM, 30 percent of those polled plant a tree for Earth Day, and 23 percent clean up a local park. About 47 percent of those polled associate Earth Day with recycling.</li>
<li>There are two simple ways to celebrate Earth Day to make the world a little better," said Nathaniel Weston, an associate professor of environmental science at Villanova University. "The first is to promote understanding of important environmental issues so that more people are aware of the critical actions we need to take to protect our environment. The second is to commit yourself to service on or around Earth Day &mdash; plant some trees, clean up a stream or help your local community garden."</li>
<li>Kate Williams, CEO of 1% for the Planet, one of the world\'s largest environmental networks, told Live Science that anyone can make a difference on Earth Day by simply incorporating little changes into their daily routines. "Read your labels, and require transparency from your favorite brands. Make a pledge to keep water clean and accessible for years to come," Williams said. "Commit to making an at-risk species your mascot, and become an advocate for that particular species. There are so many different ways to make an impact &mdash; you just have to choose one!"</li>
<li>"Take a walk in nature and simply appreciate it, plant a tree or a flower, pick up a discarded bottle and recycle it (even if it isn\'t yours), turn off your printer for a day, power off your computer and take a tech break, go vegetarian for a day, use a certified natural skin-care product. These are just a few simple ways to make a positive impact for yourself and for our Earth," Jennifer Barckley, director of brand communications and values at The Body Shop, a chain of bath and body products, told Live Science.</li>
<li>"A simple way that everyone can celebrate Earth Day to make the world a better place is to turn off the lights in their own homes and in their offices ... not just sometimes, but all of the time," said Helene King, a member of the LifeBridge Health hospitals\' Health Green Team in Baltimore. "It may sound simple, but how many times have you left the lights on when you could be saving energy?"</li>
</ul>
<p>&nbsp;</p>
<h2><strong>Earth Day Symbols</strong></h2>
<p>Symbols used by people to describe Earth Day include an image or drawing of planet earth, a tree, a flower, leaves, or the recycling symbol. Colors used for Earth Day include natural colors such as green, brown, or blue.</p>
<p>&nbsp;</p>
<p>The Earth Flag, which was designed by <a href="https://en.wikipedia.org/wiki/John_McConnell_(peace_activist)" target="_blank" rel="nofollow noreferrer">John McConnell</a>, has been described as a &ldquo;flag for all people.&rdquo; It features a two-sided dye printed image of the Earth from space on a dark blue field, made from recyclable, weather-resistant polyester. Margaret Mead believed that a flag which showed the Earth as seen from space was appropriate.</p>';
?>
