<?php
$day="Easter Monday";
$content='<h2><strong>Easter Monday </strong></h2>
<p>Easter Monday is the day after Easter Sunday, which commemorates Jesus Christ&rsquo;s resurrection, according to the Christian Bible and is observed as a holiday in some countries.</p>
<p>&nbsp;</p>
<h2><strong>Easter Monday Background</strong></h2>
<p>Easter Monday was formerly regarded as unlucky and was therefore known as Black Monday (White Monday in Greece). Many sources attribute this expression to great losses of life during military expeditions but Monday itself was generally considered unlucky. It meant returning to school after the Easter break for many school children and was also known as Bloody Monday. In medieval England women were allowed to haul out of bed any man they found there. Even Kings Edward I and Edward II went through this tradition. It was traditional for men to lift women three times by the arms and legs in northern England, where women would return the act on the following day. Easter Monday was known as the Day of the Easter Egg Bundle or the Day of Feasts in Ireland.</p>
<p><strong>&nbsp;</strong></p>
<h2><strong>Easter Monday Celebrations </strong></h2>
<p>Many Christians around the world celebrate Easter Monday as a day of rest, particularly in countries where the day is a public holiday. It is a day for many to enjoy the time outdoors in countries such as Australia and Canada. Easter parades occur in some parts of the world on Easter Monday. It is known as Dyngus, or Splash Monday, among many Polish communities where children often play water games.</p>
<p>&nbsp;</p>
<p>The United States has its own tradition, known as the Egg Roll, which occurs at the White House. This tradition can be traced as far back as 1878, although it was not always held at the White House grounds in the earlier years. It receives media attention each year. <a href="https://en.wikipedia.org/wiki/Easter_egg" target="_blank" rel="nofollow noreferrer">Easter egg</a> races are held in other parts of the world, including Germany.</p>
<p><strong>&nbsp;</strong></p>
<p>The world\'s largest organized Dyngus Day celebration occurs in Buffalo, New York. In Buffalo\'s eastern suburbs and the city\'s Historic Polonia District, Dyngus Day is celebrated with a high level of enthusiasm. Although Dyngus Day was celebrated in traditional Polish neighborhoods of Buffalo dating back to the 1870s, modern Dyngus Day in Buffalo had its start with the Chopin Singing Society. Judge Ann T. Mikoll and her late husband Theodore V. Mikoll held the first party at the Society\'s clubrooms in the Buffalo Central Terminal. The Society left the East Side in the 1980s and moved to new clubrooms in nearby Cheektowaga, where the festival attracted a new generation of revelers. In recent years, the focus of Buffalo\'s Dyngus Day celebration has returned to the Historic Polonia District in the form of large parties at the Buffalo Central Terminal, St. Stanislaus - Bishop &amp; Martyr Church, the Adam Mickiewicz Library and Dramatic Circle, and at many family-owned Polish taverns. The World\'s First Dingus Day Parade, inaugurated in 2006, makes its way through the Polonia District from the Broadway Market to Buffalo Central Terminal. In 2008, the parade attracted more than 25,000 people. In 2012, it was reported that more than 50,000 revelers attended Dyngus Day events. Local comedian "Airborne" Eddy Dobosiewicz has been a leading figure in Dyngus Day celebrations in Buffalo for several years.<strong>&nbsp;</strong></p>
<p><strong>&nbsp;</strong></p>
<h2><strong>Easter Monday Customs and Traditions</strong></h2>
<p>Easter Monday, also known as Bright Monday, Renewal Monday, Wet Monday, and Dyngus Day, is the Monday immediately after Easter Sunday. It is observed by many Christian groups, but primarily by the Eastern Orthodox and Roman Catholic traditions. It marks the beginning of Easter Week (Roman Catholic) / Bright Week (Eastern Orthodox).</p>
<p>&nbsp;</p>
<p>Different cultures observe Easter Monday very differently. For some, Easter Monday is a solemn remembrance of Christ&rsquo;s death and resurrection marked by an outdoor procession. For others, there are Easter egg-rolling competitions. For still others, siblings and/or spouses wake each other up by pouring buckets of water on each other (hence the name &ldquo;Wet Monday&rdquo;). And others celebrate with a large gathering and a polka festival (Dingus Day).</p>
<p>&nbsp;</p>
<p>Some of these observances have more Christian symbolism in them than others, but none of them are explicitly biblical. The Bible does not say anything about what happened on Easter Monday, the day after Jesus&rsquo; resurrection. The Bible does not instruct followers of Jesus Christ to observe Easter Monday, so there is no obligation to celebrate it. As with many holidays, there is nothing wrong with observing some cultural traditions, but it is important to not allow traditions to detract from the message of the gospel.</p>
<p><strong>&nbsp;</strong></p>
<h2><strong>Easter Monday Facts</strong></h2>
<ul>
<li>In the United States, Easter Monday is not a federal holiday, and is not largely observed. Even so, the day remains informally observed in some areas such as the state of North Dakota, and some cities in New York, Michigan, and Indiana. Easter Monday was a public holiday in North Carolina from 1935 to 1987. Texas and Maryland schools often have two holidays on Good Friday and Easter Monday. In some states and districts, public schools and universities are closed on Easter Monday, often part of spring break. Traditionally Polish areas of the country such as Chicago, and more recently Cleveland, observe Easter Monday as Dyngus Day. Dyngus Day celebrations are widespread and popular in Buffalo, New York; Wyandotte and Hamtramck in Michigan; South Bend and La Porte in Indiana; and Hanover, New Hampshire. Another important custom is the White House Easter egg roll.</li>
<li>In Germany, people go out into the fields early in the morning and hold Easter egg races. For Roman Catholics, Easter Monday is also a Holy Day of Obligation in Germany.</li>
<li>In Australia, Easter Monday is a public holiday. People enjoy outdoor sporting events, such as the Oakbank Easter Racing Carnival in South Australia, Australian Three Peaks Race in Tasmania (Ceased in 2013) and the Stawell Gift in Victoria.</li>
<li>In Austria and Southern Germany, there is the traditional "Emmausgang", commemorating the walk of the disciples to Emmaus, to which Jesus followed them without being recognized.</li>
<li>In Canada, Easter Monday is the imminent Monday following Easter Sunday and is a statutory holiday for federal employees. Although not mandatory by federal regulation, many employers also give this day off to employees out of common practice. Additionally, this holiday succeeds Good Friday (the Friday preceding Easter), which is a mandatory holiday for all employees, giving workers an extra-long weekend in April. In provinces where Family Day, Islander Day and Louis Riel Day are not observed Easter Weekend is the first stat holiday after New Year&rsquo;s Day</li>
</ul>
<p>&nbsp;</p>
<ul>
<li>In Egypt, the ancient festival of Sham El Nessim (Arabic: شم النسيم&lrm;, literally meaning "smelling of the breeze") is celebrated on the Coptic (i.e. Eastern) Easter Monday, though the festival dates back to Pharonic times (about 2700 BC). It is an Egyptian national holiday. Traditional activities include painting eggs, taking meals outdoors, and eating feseekh (fermented mullet).</li>
<li>In the Republic of Ireland, it is a day of remembrance for the men and women who died in the Easter Rising which began on Easter Monday 1916. Until 1966, there was a parade of veterans, past the headquarters of the Irish Republican Army at the General Post Office (GPO) on O\'Connell Street, and a reading of the Proclamation of the Irish Republic.</li>
<li>Śmigus-dyngus (or lany poniedziałek, Polish for Wet Monday) is the name for Easter Monday in Poland and the diaspora. In the Czech Republic it is called velikonočn&iacute; ponděl&iacute;. In Slovakia veľkonočn&yacute; pondelok, also called &Scaron;ibačka/Polievačka or Oblievačka. In Hungary h&uacute;sv&eacute;th&eacute;tfő. All countries practice a unique custom on this day. In Poland, Hungary, Slovakia, and the Czech Republic traditionally, early in the morning boys awake girls by pouring a bucket of water on their head and striking them about the legs with long thin twigs or switches made from willow, birch or decorated tree branches. Another related custom, unique to Poland, is that of sprinkling bowls (garce) of ashes on people (starts men on women) or houses, celebrated a few weeks earlier at the "p&oacute;łpoście". This custom is almost forgotten, but still practiced in the area around the borders of Masuria and Masovia.</li>
<li>Formerly, the post-Easter festivities involved a week of secular celebration, but in many places this was reduced to one day in the 19th century. Events include egg rolling competitions and, in predominantly Roman Catholic countries, dousing other people with water which traditionally had been blessed with holy water the day before at Easter Sunday Mass and carried home to bless the house and food</li>
</ul>
<p><strong>&nbsp;</strong></p>
<h2><strong>Easter Monday Symbols</strong></h2>
<p>For people with strong Christian beliefs, the cross that Jesus was crucified on and his resurrection are important symbols of the period around Easter. Other symbols of Easter include real eggs or eggs manufactured from a range of materials, nests, lambs and rabbits or hares. Sometimes these symbols are combined, for example, in candy models of rabbits with nests full of eggs. Eggs, rabbits, hares and young animals are thought to represent the re-birth of nature in the spring.</p>';
?>
