<?php
$day="Flag Day";
$content='<h2><strong>Flag Day</strong></h2>
<p>The Fourth of July was traditionally celebrated as America\'s birthday, but the idea of an annual day specifically celebrating the Flag is believed to have first originated in 1885. &nbsp;BJ Cigrand, a schoolteacher, arranged for the pupils in the Fredonia, Wisconsin Public School, to observe June 14 which is the 108th anniversary of the official adoption of The Stars and Stripes as \'Flag Birthday\'. In numerous magazines and newspaper articles and public addresses over the following years, Cigrand continued to enthusiastically advocate the observance of June 14 as \'Flag Birthday\', or \'Flag Day\'.</p>
<p><strong>&nbsp;</strong></p>
<h2><strong>Flag Day Background</strong></h2>
<p>The first celebration of the birthday of the <a href="https://en.wikipedia.org/wiki/Flag_of_the_United_States" target="_blank" rel="nofollow noopener">US Flag</a> was held in 1877 on the 100th anniversary of the 1777 Flag Decision. However, it is thought that the first year of the flag\'s birthday was recognized in 1885, the first date that school teacher BJ Cigrand was held. 108th anniversary of the official adoption of Stars and Stripes as Flag Birthday - a group of Wisconsin school children to be observed on June 14th. Cigrand, now known as the Flag Day Father, continued to defend his observation of the flag as \'birthday\' or <strong>\'Flag Day\'</strong> on June 14 for many years.</p>
<p>&nbsp;</p>
<p>Just a few years later, the efforts of another school teacher, George Balch, led to the official monitoring of \'Flag Day\' by the New York State Education Board on 14 June. In the following years, up to 36 states and local governments began observations annually. For over 30 years Flag Day remained as a state and local celebration.</p>
<p>The anniversary of the 1777 Flag Decision in 1916 was a nationally observed event announced by President Woodrow Wilson. However, it was not designated National Flag Day until August 3, 1949, when a Law on Congress set 14 June as the National Flag Day each year.</p>
<p>&nbsp;</p>
<p><span style="text-decoration: underline;">Flag Day</span> is widely celebrated with parades, essay contests, ceremonies, and picnics sponsored by veterans\' groups, schools, and groups like the National Flag Day foundation. National <em>Flag Day</em> foundation\'s goal is to preserve the traditions, history, pride, and respect that are due the nation\'s symbol, Old Glory. Strong evidence shows that Francis Hopkinson of New Jersey, a signer of the Declaration of Independence, was responsible for the stars in the U.S. flag.</p>
<p>At the time that the flag resolution was adopted, Hopkinson was the Chairman of the Continental Navy Board\'s Middle Department. Hopkinson also helped design other devices for the Government including the Great Seal of the United States. For his services, Hopkinson submitted a letter to the Continental Admiralty Board asking "whether a Quarter Cask of the public Wine will not be a proper &amp; reasonable Reward for these Labors of Fancy and a suitable Encouragement to future Exertions of a like Nature." His request was turned down since the Congress regarded him as a public servant.</p>
<p><strong>&nbsp;</strong></p>
<h2><strong>Flag Day Celebrations</strong></h2>
<p>Hundreds of Flag Day parades, concerts and other events are being held across the country to celebrate the holiday. Philadelphia\'s annual Stripes and Stars Festival, which also commemorates the US Army\'s anniversary, will include a flag-raising ceremony, a parade, a skydiving performance and a naturalization ceremony for new citizens. Many other cities and towns also are hosting events to commemorate veterans and military families. You may attend them as an audience or you may choose to be a volunteer to take a part in them.</p>
<p>&nbsp;</p>
<h2><strong>Flag Day Customs and Traditions</strong></h2>
<p>Some historical museums have Flag Day themed programming and exhibitions to contextualize the importance of the festival. The Museum of American Revolution in Philadelphia uses a collection of 40 historic 13-star US flags representing 13 original colonies. You can explore the program in your local museum and do research to educate yourself about the cultural significance of the day.</p>
<p>You may also visit one of the nation\'s 136 veterans\' cemeteries or maybe a veterans\' memorial or monument to commemorate fallen soldiers. Well-known sites include The Prison Ship Martyrs Monument in New York, the Tomb of the Unknown Soldier at Arlington National Cemetery, The American Veterans Disabled For Life Memorial in Washington and the California Vietnam Veterans Memorial.</p>
<p><strong>&nbsp;</strong></p>
<h2><strong>Flag Day Facts</strong></h2>
<ul>
<li>Inspired by these three decades of state and local celebrations, Flag Day - the anniversary of the Flag Resolution of 1777 - was officially established by the Proclamation of President Woodrow Wilson on May 30th, 1916. While Flag Day was celebrated in various communities for years after Wilson\'s proclamation, it was not until August 3rd, 1949, that President Truman signed an Act of Congress designating June 14th of each year as National Flag Day.</li>
<li>The Stars and Stripes originated as a result of a resolution adopted by the Marine Committee of the Second Continental Congress at Philadelphia on June 14, 1777. The resolution read: "Resolved, that the flag of the United States be thirteen stripes, alternate red and white; that the union be thirteen stars, white in a blue field representing a new constellation. "</li>
<li>The resolution gave no instruction as to how many points the stars should have, nor how the stars should be arranged on the blue union. Consequently, some flags had stars scattered on the blue field without any specific design, some arranged the stars in rows, and some in a circle. The first Navy Stars and Stripes had the stars arranged in staggered formation in alternate rows of threes and twos on a blue field. Other Stars and Stripes flags had stars arranged in alternate rows of four, five and four. Some stars had six points while others had eight.</li>
<li>The Star-Spangled Banner Flag House in Baltimore, Maryland birthplace of the flag that a year later inspired Francis Scott Key (1779&ndash;1843), to pen his famous poem, has celebrated Flag Day since the inception of a museum in the home of flag-banner-pennant maker Mary Pickersgill on the historic property in 1927. The annual celebrations on Flag Day and also Defenders Day (September 12, since 1814) commemorates the Star-Spangled Banner and its creator Mary Pickersgill, for the huge emblem that flew over Fort McHenry guarding Baltimore harbor during the British Royal Navy\'s three days attack in the Battle of Baltimore during the War of 1812 (1812&ndash;1815).</li>
<li>The Betsy Ross House, home of legendary Betsy Ross has long been the site of Philadelphia\'s observance of Flag Day.</li>
<li>June 14 is also the date for the annual anniversary of the Bear Flag Revolt in California. On June 14, 1846, 33 American settlers and mountain men arrested the Mexican general in command at Sonoma, and declared the "Bear Flag Republic" on the Pacific Ocean coast as an independent nation. A flag emblazoned with a bear, a red stripe, a star and the words "California Republic" was raised to symbolize independence from Mexico of the former province of Alta California. The Bear Flag was adopted as California\'s state flag upon joining the Union as the 31st state in 1850, after being annexed after by the United States following the Mexican&ndash;American War of 1846-1849.</li>
</ul>
<p>&nbsp;</p>
<h2><strong>Flag Day Symbols</strong></h2>
<p>The current US flag, with its 13 stripes and 50 stars, has been around more than 50 years. But before that, people got creative with their flag interpretations. Check out historic flags and a handful of rejected designs at the online archives of the Eisenhower Presidential Library &amp; Museum in Abilene, Kansas. US state flags have all kinds of quirky and surprising origin stories. Consider the California flag, the symbol of a settlers\' revolt in 1846, and Alaska\'s flag, designed in 1927 by a 13-year-old boy. It is widely believed that Betsy Ross, who assisted the Revolutionary War effort by repairing uniforms and sewing tents, made and helped design the first American flag. However, there is no historical evidence that she contributed to Old Glory&rsquo;s creation. It was not until her grandson William Canby held an 1870 press conference to recount the story that the American public learned of her possible role.</p>
<p>The lyrics of &ldquo;The Star-Spangled Banner,&rdquo; America&rsquo;s national anthem since 1931, are taken from a patriotic poem written by Francis Scott Key after he witnessed the Battle of Fort McHenry during the War of 1812. His words were set to the tune of &ldquo;To Anacreon in Heaven,&rdquo; a popular British drinking song.</p>
<p>In the 1950s, when it seemed certain that Alaska would be admitted to the Union, designers began retooling the American flag to add a 49th star to the existing 48. Meanwhile, a 17-year-old Ohioan student Bob Heft borrowed his mother&rsquo;s sewing machine, disassembled his family&rsquo;s 48-star flag and stitched on 50 stars in a proportional pattern. He handed in his creation to his history teacher for a class project, explaining that he expected Hawaii would soon achieve statehood as well. Heft also sent the flag to his congressman, Walter Moeller, who presented it to President Eisenhower after both new states joined the Union. Eisenhower selected Heft&rsquo;s design, and on July 4, 1960, the president and the high school student stood together as the 50-star flag was raised for the first time. Heft&rsquo;s teacher immediately changed his grade from a B- to an A.</p>';
?>
