<?php
$day="Mardi Gras Carnival";
$content='<h2><strong>Mardi Gras Carnival </strong></h2>
<p>The Mardi Gras Carnival, also known as Fat Tuesday or Shrove Tuesday, is a colorful carnival with music, parades, picnics, floats and excitement and marks the last day before the period of Lent, when many Christians traditionally fast or give up a chosen luxury in the lead-up to Easter. It starts on Tuesday between 3<sup>rd</sup> of February and 9<sup>th</sup> of March, depending on the date of Easter. For example, Fat Tuesday in 2019 was on Tuesday, March 5 and in 2020 will be on Tuesday February 25.</p>
<p>The source of the name Mardi Gras comes from French. It literally means &ldquo;Fat Tuesday&rdquo;. This is because it is the last day that you eat richer, &ldquo;fatty&rdquo; foods before the ritual fasting of the Lenten season, which begins on Ash Wednesday. Mardi Gras, a celebration of French origin, has migrated from Europe to the Americas through immigrants. One of the biggest Mardi Gras carnivals takes place in New Orleans. Celebrations sometimes last for days and they are quite colorful. In addition to the carnivals where the participants are dressed in colorful clothes or costumes, dance and theater performances, sports competitions and food and beverage festivals are held.</p>
<p>&nbsp;</p>
<h2><strong>Mardi Gras Carnival Background</strong></h2>
<p>Mardi Gras is a tradition that dates back thousands of years, including the festivities of Saturnalia and Lupercalia, and celebrates spring and fertility. Mardi Gras was originally celebrated in medieval Europe, especially in Italy and France. The first recording of a Mardi Gras celebration in the United States in the early 1700s. The celebrations took place in New Orleans and were more like fancy balls or dances. The atmosphere of the carnival did not happen later in the 1700s. The first Mardi Gras parades began in the 1800s, and the king of the parade became a regular symbol of the festivals. Mardi Gras was declared a legal holiday in Louisiana in 1875.</p>
<p>When Christianity came to Rome, religious leaders decided to incorporate these popular local traditions into the new faith rather than completely eliminate them. As a result, the over-consumption and entertainment of the Mardi Gras season is the start of Lent, a 40-day fast between Ash Wednesday and Easter Sunday. With Christianity, Mardi Gras spread from Rome to other European countries, including France, Germany, Spain and the United Kingdom.</p>
<p>Mardi Gras was a holiday in 1582 that Pope Gregory XIII placed on the Gregorian calendar the day before Ash Wednesday. The holiday reached North America in the late 17th century with the LeMoyne brothers. He came to defend France\'s claim to Louisiana, and in 1699 they introduced the celebration to a local party with a party on the Mississippi River.</p>
<p>The parties continued for the next few decades until the Spanish took over New Orleans in the 1760s and tried to close what they saw as immoral celebrations. The restrictions continued until the US Government took over in the early 1800s. From that time until 1837, the holiday was accepted but not encouraged.</p>
<p>&nbsp;</p>
<h2><strong>Mardi Gras Carnival Celebrations </strong></h2>
<p>The <strong>Mardi Gras Carnival</strong> is celebrated today as a gigantic street party around the world in New Orleans, where it was brought by the French. The groups that organize the festival are called \'krewe\'. They are a kind of club, with dues ranging from 20 to thousands of dollars per year. They also have their own parties, ball and parades. The best known krewelar are Zulu (a tradition of thematic parades), Rex Bacchus (famous for being the first to reveal the purple, yellow, green, accepted in Mardi Gras colors) and Endymion (both featuring famous stars in the cast). The Krewe of Muses is made up of women and is named after the Museums, the daughters of Zeus. If you have a dog you will be very happy here. Because it will also have its own parade organized by Krewe of Barkus.</p>
<p>Famous Mardi Gras beads are thrown into the festival crowd on walks and horse-drawn parades. You need to be careful not to get hurt, not to step on the scattered beads. People also throw stuffed animals, toys and more. The beads were first discarded by Santa Claus during the parade in the early 1900s. They were not synonymous with flashing until a few decades ago.</p>
<p><strong>&nbsp;</strong></p>
<h2><strong>Mardi Gras Carnival Customs and Traditions</strong></h2>
<p>An important tradition of Mardi Gras is food. It is an excellent opportunity to try the famous <strong>New Orleans</strong> cuisine with all its beauties. Don\'t miss the desserts (strawberries, cinnamon and cream cake) called <a href="https://en.wikipedia.org/wiki/King_cake" target="_blank" rel="nofollow noreferrer">King Cake</a> in particular. During Mardi Gras, carnival participants can find this great taste everywhere.</p>
<p>Anise liqueur, known as Ojen, is widely consumed in the <span style="text-decoration: underline;">Mardi Gras Carnival period</span>, as in Jambalaya, a classic Creole dish of rice, meat and vegetables.</p>
<p><strong>&nbsp;</strong></p>
<h2><strong>Mardi Gras Carnival Facts</strong></h2>
<p><strong>&nbsp;</strong></p>
<ul>
<li>People in Ireland, England, Australia, New Zealand, and Canada, celebrate Mardi Gras Carnival season by eating pancakes and participating in pancake themed activities.</li>
<li>The king cake (or three kings&rsquo; cake) is eaten all over the world during the carnival season. In the United States, the King\'s Cake contains a trinket baby Jesus and is traditionally purple, green and gold. Whoever takes baby Jesus is said to have good luck throughout the year!</li>
<li>New Orleans has been celebrating Fat Tuesday with parades since 1837. The first floating appeared in the parade in 1857.</li>
<li>Fat Tuesday is an official state holiday in the Alabama, Florida and Louisiana regions. Although there is no state holiday in Texas, Galveston is hosting one of the country\'s biggest celebrations.</li>
<li>Thousands of tourists come to New Orleans every year for the Mardi Gras celebrations, but it is also a fact that it is not the first recorded festival location in the US. The original Mardi Gras started in 1703 in Mobile, Alabama. New Orleans would not be established for another 15 years. The festival began as a French Catholic tradition and is now celebrated by many people throughout the city, regardless of religious ties. During the Mardi Gras celebrations in Mobile, many schools and even some businesses were closed.</li>
<li>It is illegal to ride a float without wearing a mask during the Mardi Gras celebrations. The main purpose of the mask was to eliminate the community of social constraints for one day and to allow different classes and groups to socialize freely during the celebrations.</li>
<li>The date of Mardi Gras Carnival is different every year. The reason for this is that it is related to the Easter of which date is also changing every year. Easter falls on the first Sunday after the first full moon on or after March 21. Mardi Gras is usually held 47 days before Easter. The dates of Mardi Gras are between 3 February and 9 March.</li>
<li>There are other names for Mardi Gras Carnival in other parts of the world include Martes de Carnaval (in Mexico), Karneval (Germany), J\'Ouvert (Trinidad), Fastan (Sweden), and Martedi Grasso (Italy).</li>
<li>For Mardi Gras, a French Cajun expression is "Laissez les bons temps rouler", meaning " Let the good times roll."</li>
<li>With the city\'s large population and the many tourists visiting New Orleans for Mardi Gras, it is not surprising that the festival is a major part of the local economy. At a single Mardi Gras festival, anywhere between $ 144 and $ 500 million comes into the economy. The cost of participating in the show is a bit expensive, some over $ 100,000.</li>
<li>Mardi Gras Carnival, which began during the Pagan celebrations, has become a crazy, fun-filled event to be believed. With balls, parades, masks and indulgence with food and drink, Mardi Gras is one of the truly unique holidays in the world.</li>
</ul>
<p>&nbsp;</p>
<h2><strong>Mardi Gras Carnival Symbols</strong></h2>
<ul>
<li>Mardi Gras colors are purple, green and gold. In 1892, the Rex parade theme "Symbolism of Colors" gave meaning to these colors. Purple Represents Justice. Green Represents Faith. Gold Represents Power.</li>
<li>King cake is another symbol of Mardi Gras Carnival which resembles a coffee cake rather than a traditional cake, and is made with hand-braided dough that is topped with cinnamon and sugar.</li>
<li>With a strong French influence throughout Southern Louisiana and the Gulf Coast, Fleur De Lis became a popular symbol and is often used in the throws and decorations of Mardi Gras. The symbol appeared on the flag of the French explorer Sieur de La Salle, who founded the Mississippi Valley. Later, when the French settlers founded New Orleans in 1718, they continued to use this symbol.</li>
<li>Little plastic colorful beads, especially in green, purple, and gold, are not only found in New Orleans during the Mardi Gras season. They are everywhere, even in the trees and people\'s porch railing.</li>
<li>One of the most famous symbols of the celebrations is Mardi Gras masks. The practice of masking is based on the European Carnival celebrations, and some think that the roots of pagan Rome\'s celebration traditions are far ahead. Mardi Gras masks give rebels an air of mystery and magic. One of the main advantages of masking for Mardi Gras is that parades and parties are concealed from one\'s identity.</li>
</ul>';
?>
