<?php
$day="New Year's Day";
$content='<h2><strong>New Year&rsquo;s Day</strong></h2>
<p>New Year&rsquo;s Day is internationally celebrated on the first day of each year. <a href="https://www.onthisday.com/events/january/1" target="_blank">January 1st</a> has a unique meaning apart from being a date that refers to the beginnings. It is beginning of the year as well as of new decisions and plans. Therefore, the date is an international holiday celebrated in many countries as New Year&rsquo;s Day all around the world. It is also a federal public holiday in many countries. It means, all schools, government offices, banks, official and private businesses is closed on this day.</p>
<p>New Year&rsquo;s Day is also the last day of the week-long Christmas-New Year holidays. Therefore, this day is considered as the last and therefore the most valuable day of the holiday. It is desirable to spend the first day of the year and the last day of the holiday in the best way before continuing with responsibilities such as work and school.&nbsp;</p>
<h2><strong>New Year&rsquo;s Day Background</strong></h2>
<p>The early Roman calendar which is believed to be created by Romulus, the founder of Rome, in the eighth century B.C consisted of 10 months and 304 days. Then the king Numa Pompilius, is added the months of Januarius and Februarius to the Roman calendar. in 46 B.C, the emperor Julius Caesar decided to solve the problem of being out of sync by consulting with the most prominent astronomers and mathematicians of his time. After the studies, he introduced the Julian calendar, which closely resembles the more modern Gregorian calendar that most countries use today. Related to his reform, Caesar instituted January 1 as the first day of the year. He honored the month&rsquo;s name with Janus, the Roman god of beginnings, whose two faces allowed him to look back into the past and forward into the future.</p>
<p>New Year\'s is one of the oldest celebrated holidays. It was first observed 4000 years ago in ancient Babylon, in the spring equinox (last days of the March). The celebration lasted for 11 days. During the festival, the king took off his formal clothes so that everyone could do whatever they wanted for a few days. At the end of the holiday, the king dressed again in fine robes and everyone went back to work.</p>
<p><strong>&nbsp;</strong></p>
<h2><strong>New Year&rsquo;s Day Celebrations </strong></h2>
<p>Many cultures celebrate this happy day in their own unique way. Typically, the celebrations of the New Year&rsquo;s Day include a variety of foods, drinks and gathering together with the loved ones. New Year is also considered as a blank sheet of paper to be filled with new happy events and celebrations. The New Year is a great opportunity for many to take lessons from the previous year and make positive changes in their lives.</p>
<p>While early celebrations were more paganistic in nature, celebrating Earth&rsquo;s cycles, Christian tradition celebrates the Feast of the Circumcision of Christ on New Year&rsquo;s Day. Roman Catholics also often celebrate Solemnity of Mary, Mother of God, a feast honoring Mary. However, in the twentieth century, the holiday grew into its own celebration and mostly separated from the common association with religion. Although many people still follow older traditions, New Year\'s Day has become a holiday associated with nationality, relationships, and introspection rather than a religious celebration. In many places, there are fireworks, concerts and parades during New Year\'s Eve celebrations. People gather in their homes or in the most crowded and touristic squares of the city, enter the first day of the year by singing, dancing, eating, drinking and having fun.</p>
<p><strong>&nbsp;</strong><strong>&nbsp;</strong></p>
<h2><strong>New Year&rsquo;s Day Customs and Traditions</strong></h2>
<p>&nbsp;</p>
<ul>
<li>Many English-speaking countries play &ldquo;Auld Lang Syne,&rdquo; a song celebrating the year&rsquo;s happy moments. Americans often make resolutions and watch the Time Square Ball drop in New York City. Although much of this celebration occurs the night before, they typically continue to New Year&rsquo;s Day. Football is a common fixture on New Year&rsquo;s Day in America, usually the day of the Rose Bowl. Some foods considered &ldquo;lucky&rdquo; to eat during the festivities include circular shaped foods, black-eyed peas and cabbage.</li>
<li>In the French culture, the new day&rsquo;s weather is considered as a forecast for the upcoming year&rsquo;s harvest, taking into account aspects like wind direction to predict the fruitfulness of crops and fishing.</li>
<li>Spanish people celebrate New Year&rsquo;s Day with the custom of eating twelve grapes, each eaten at a clock-stroke at midnight.</li>
<li>In Japan, people hang a rope of straw in front of their houses signifying happiness and good luck. They believe it keeps the evil spirits away. Japanese people begin to laugh the moment the New Year begins, so they will have good luck the whole year.</li>
<li>The Chinese New Year is celebrated sometime between January 21 and February 20, at the time of the new moon, and it is called \'Yuan Tan\'. The New Year is ushered in with the lighting of firecrackers at midnight on the eve of the Chinese Lunar Calendar. The Chinese shop for Oranges (they believe it brings good luck), clean their homes and settle all debts.</li>
<li>Celebration of the Hindu New Year varies based on geographic location. Most Hindus live in India, but many have different traditions. For example, the Hindus of Gujarat, in western India, celebrate the New Year at the end of October, at the same time as the Indian festival of Diwali. For the Diwali celebration, small oil lights are lit all along the rooftops. In northern India, people wear flowers to celebrate the New Year&rsquo;s Day, commonly in pink, red, purple, or white hues. Hindus in central India display orange flags, flying them from the top of buildings. In southern India, mothers put food, flowers, and small gifts on a special tray. On New Year\'s morning, children must keep their eyes shut until they have been led to the tray.</li>
<li>The Jewish New Year is called Rosh Hashanah, and falls in the seventh month, or Tishri, of the Jewish calendar (September - October). Rosh Hashanah is a holy time when people reflect on the things they have done wrong in the past, so they can improve in the future. Celebration of the New Year begins at sunset the day before, and religious services are held at synagogues in observation. An instrument called a Shofar, made from a ram\'s horn, is traditionally played and children are given new clothes to celebrate the New Year&rsquo;s Day. In addition, New Year loaves are baked and fruit is eaten to remind people of harvest time.</li>
<li>In Scotland they celebrate Hogmanay. In some villages, they burn barrels of tar and roll them through the streets, showing that the old year is burned up and the new one can begin.</li>
<li>People living in Turkey, generally end the year with a countdown, but New Year&rsquo;s Day parties and street performances last until dawn. Late celebrations are also common for house parties with friends and relatives and festivities at hotels and restaurants. The morning of January 1 is usually quiet.</li>
</ul>
<p>&nbsp;</p>
<p>For thousands of years, New Year&rsquo;s has been a festival of rebirth and reflection, allowing people all over the world to celebrate another great year.</p>
<p>On New Year\'s Day, many towns and cities run events, often people try to recover from the night, or begin to speak, write, and plan their &ldquo;New Year\'s Resolutions&rdquo;.</p>
<p><strong>&nbsp;</strong><strong>&nbsp;</strong></p>
<h2><strong>New Year&rsquo;s Day Resolutions</strong></h2>
<p>The decision-making tradition dates back to the early Babylonians. Babylon\'s most popular resolution was to take back the borrowed agricultural equipment. Today\'s resolutions are a secular version of past religious vows. Popular modern resolutions might include the promise to lose weight or quit smoking.</p>
<p>Although celebrations vary by culture, it is certain that the new year is an excellent opportunity for new decisions. And those decisions are almost the same, like the followings:</p>
<ul>
<li>Making resolutions or goals to improve the quality of life.</li>
<li>Common resolutions concern diet, exercise, bad habits, and other issues concerning personal wellness. A common view is to use the first day of the year as a clean slate.</li>
<li>Knowing the value of their loved ones, spend more, quality time with them. It is also decided to spend more time with parents, to visit elderly relatives, to tell our loved ones that we love them more.</li>
<li>To understand the value of what you have, to be more thankful, less regret. To put an end to hatred, oversensitiveness and resentment.</li>
</ul>
<p>&nbsp;</p>
<h2><strong>New Year&rsquo;s Day Symbols</strong></h2>
<p>A new born baby is one of the common symbols of the New Year&rsquo;s Day. According to mythology, Baby New Year grows up and ages in a single year. At the end of the year it becomes an old person and hands the role over to the next Baby New Year.</p>
<p>The other symbol of New Year&rsquo;s Day is the color of red. Around the world red is worn to bring love, luck, prosperity and good fortune, which are popular wishes for a new year. Red color refers to divine energy of the fire, that is why it is the color of love and happiness in Chine, the marriage color in India and the color of passion in the West.</p>
<p>Therefore, people prefer to wear red underwear, clothing and accessories during the New Year&rsquo;s Day celebrations.</p>
<p>&nbsp;</p>';
?>
