<?php
$day="Pentecost";
$content='<h2><strong>Pentecost</strong></h2>
<p><strong>Pentecost</strong> is the day that the church was born. Christians have been celebrating the church&rsquo;s birthday with joy and exuberance for two millennia. Pentecost or Pentecost Sunday takes place 40 days after Easter Sunday. <span style="text-decoration: underline;">Pentecost</span> was originally a Jewish holiday what was held 50 days after Passover as one of the major Jewish feasts.</p>
<p>In the Christian tradition, Pentecost is the celebration of the person of the <a href="https://thebibleproject.com/explore/holy-spirit/" target="_blank" rel="nofollow noopener">Holy Spirit</a> coming upon the Apostles, Mary, and the first followers of Jesus, who were gathered together in the Upper Room. Pentecost always occurs 50 days after the death and resurrection of Jesus, and ten days after his ascension into heaven. Because Easter is not a fixed date, and Pentecost depends on the date of Easter, Pentecost is also a moveable day which can fall anywhere between May 10 and June 13 each year.</p>
<p><strong>&nbsp;</strong></p>
<h2><strong>Pentecost Background</strong></h2>
<p>The word Pentecost comes from the Greek word for &ldquo;fiftieth&rdquo; (pentecoste), because it is the fiftieth day (Greek, pentecoste hemera) after Easter Sunday (on the Christian calendar). This name came into use in the late Old Testament period and was inherited by the authors of the New Testament. According to the Bible&rsquo;s New Testament the apostles were inspired to talk in tongues when the Holy Spirit descended on to them as they prayed together at the Shavuot festival. Hearing audiences speak in an unfamiliar language, gathered audience in Jerusalem believed they were drunk. But Saint Peter told them that the apostles were inspired by the spirit and delivered the first Christian sermon, leading to the transformation and baptism of 3,000 people. Because of Peter\'s sermons, many see the Pentecost the birth of the Christian church as an official movement. Pentecost Sunday is a commemoration and celebration of the receiving of the Holy Spirit by the early church. John the Baptist prophesied of the first Pentecost when Jesus would baptize with the Holy Spirit and with fire (Matthew 3:11).</p>
<p>&nbsp;</p>
<h2><strong>Pentecost Celebrations</strong></h2>
<ul>
<li>Typically, priests will wear red vestments on Pentecost, symbolic of the burning fire of God&rsquo;s love and the tongues of fire that descended on the apostles.</li>
<li>However, in some parts of the world, Pentecost is also referred to as &ldquo;WhitSunday&rdquo;, or White Sunday, referring to the white vestments that are typically worn in Britain and Ireland. The white is symbolic of the dove of the Holy Spirit, and typical of the vestments that catechumens desiring baptism wear on that day.</li>
<li>An Italian Pentecost tradition is to scatter rose leaves from the ceiling of the churches to recall the miracle of the fiery tongues, and so in some places in Italy, Pentecost is sometimes called Pascha Rosatum (Easter roses).</li>
<li>In France, it is tradition to blow trumpets during Mass to recall the sound of the driving wind of the Holy Spirit.</li>
<li>In Asia, it is typical to have an extra service, called genuflexion, during which long poems and prayers are recited. In Russia, Mass goers often carry flowers or green branches during Pentecost services.</li>
</ul>
<p><strong>&nbsp;</strong></p>
<h2><strong>Pentecost Customs and Traditions</strong></h2>
<p>Pentecost is celebrated to recognize the gift of the Holy Spirit, realizing that God&rsquo;s very life, breath and energy live in believers. There are many Pentecost customs and traditions followed many Christian churches today. In some churches, baptisms are performed throughout the day. Pentecost Sunday is also known as &ldquo;Whitsunday&rdquo;, because of the &ldquo;white&rdquo; garments worn by those who are baptized. In most Pentecost services, priests or church officials wear red vestments. Sanctuaries are decorated with images of flame, wind and pigeons. Churches in Italy emit rose petals from the ceiling to symbolize the languages of fire described in the Book of the Acts. French churches play trumpets throughout the ministry to assert that the Holy Spirit comes with a strong wind. Most Pentecost videos show the power and importance of these early signs of the Holy Spirit. Both Catholic and Protestant services have Scripture readings from the books of Isaiah, Ezekiel, Joel, or Acts.</p>
<p><strong>&nbsp;</strong></p>
<h2><strong>Pentecost Facts</strong></h2>
<p>Here are the interesting and informative facts about the Pentecost:</p>
<ul>
<li>Pentecost marks the fullness of God coming to the earth and interacting with humanity, as Christians understand it. God the Father has always been there, present in creation and all around us. Christ Jesus came to earth in the form of a human to take away the sins of the world. And the Holy Spirit came at Pentecost to stay forever within the souls of humans, a \'spirit of truth,\' a \'counselor.\' It\'s the inner voice that Christians rely on for guidance and that they listen for during prayer. It\'s the energy that mobilizes churches to work together to serve their communities and get things done. That\'s the Holy Spirit, and Pentecost is the day it first came down in a very spectacular form.</li>
<li>The Holy Spirit allowed the apostles to speak in other languages, and they started preaching the word of Jesus to the Jews who were in Jerusalem for the feast of Shavuot (also known as the Feast of Weeks or Pentecost - in this case, meaning seven weeks since Passover).</li>
<li>Many Christians recognize the Descent of the Holy Spirit as the birth of the Church.</li>
<li>In the United Kingdom, Pentecost is known as Whitsunday. The name "Whitsunday" is generally attributed to the white garments formerly worn by the candidates for baptism on this feast.</li>
<li>In Germany, Pentecost is called "Pfingsten" and often coincides with the beginning of many outdoor and springtime activities.</li>
<li>In the Old Testament, new Christians were first given the Holy Spirit as recorded in Acts 2:1-13. &ldquo;When the day of Pentecost came, they were all together in one place,&rdquo; says Acts 2:1-4 in the New International Version. &ldquo;Suddenly a sound like the blowing of a violent wind came from heaven and filled the whole house where they were sitting. They saw what seemed to be tongues of fire that separated and came to rest on each of them. All of them were filled with the Holy Spirit and began to speak in other tongues as the Spirit enabled them.&rdquo;</li>
<li>Jews celebrate Pentecost, too. The Jewish people celebrate Pentecost 50 days after Passover ends. In the Jewish faith, believers celebrate Passover (of the &ldquo;Shavuoth,&rdquo; or feast of weeks festival) to remember how God gave Moses the Ten Commandments as recorded in Exodus, in the Old Testament. The Jewish festival foreshadows the coming of a Messiah.</li>
<li>As the Book of Acts explains, the Christians were &ldquo;utterly amazed&rdquo; at the events happening when the Holy Spirit first came upon them. &ldquo;Now there were staying in Jerusalem God-fearing Jews from every nation under heaven,&rdquo; Acts 2:5-8 says. &ldquo;When they heard this sound, a crowd came together in bewilderment, because each one heard his own language being spoken. Utterly amazed, they asked: &lsquo;Aren&rsquo;t all these who are speaking Galileans? Then how is it that each of us hears them in our native language?\'&rdquo; Scripture goes on to say, in Acts 2:9-12: &ldquo;&lsquo;Parthians, Medes and Elamites; residents of Mesopotamia, Judea and Cappadocia, Pontus and Asia, Phrygia and Pamphylia, Egypt, and the parts of Libya near Cyrene; visitors from Rome (both Jews and converts to Judaism); Cretans and Arabs &mdash; we hear them declaring the wonders of God in our own tongues!&rsquo; Amazed and perplexed, they asked one another, &lsquo;What does this mean?\'&rdquo;</li>
<li>About 3,000 people converted to Christianity on the first day of Pentecost. According to the Bible, those who repent and turn to Jesus receive the Holy Spirit.</li>
</ul>
<p><strong>&nbsp;</strong></p>
<h2><strong>Pentecost Symbols</strong></h2>
<p>The icon of the Feast of Pentecost is known as "The Descent of the Holy Spirit". It is an icon of bold colors of red and gold signifying that this is a great event. The movement of the icon is from the top to the bottom. At the top of the icon is a semicircle with rays coming from it. The rays are pointing toward the Apostles, and the tongues of fire are seen descending upon each one of them signifying the descent of the Holy Spirit. The building in the background of the icon represents the upper room where the Disciples of Christ gathered after the Ascension. The Apostles are shown seated in a semicircle which shows the unity of the Church. Included in the group of the Apostles is Saint Paul, who, though not present with the others on the day of Pentecost, became an Apostle of the Church and the greatest missionary. Also included are the four Evangelists, Matthew, Mark, Luke, and John, holding books of the Gospel, while the other Apostles are holding scrolls that represent the teaching authority given to them by Christ.</p>
<p>In the icon of Pentecost, we see the fulfillment of the promise of the Holy Spirit, sent down upon the Apostles who will teach the nations and baptize them in the name of the Holy Trinity. We also see that the Church is brought together and sustained in unity through the presence and work of the Holy Spirit, that the Spirit guides the Church in the missionary endeavor all around the world, and that the Spirit nurtures the Body of Christ, the Church.</p>';
?>
