<?php
$day="Veterans' Day";
$content='<h2><strong>Veterans&rsquo; Day</strong></h2>
<p><strong>Veterans&rsquo; Day</strong>, formerly known as Armistice Day, was originally set as a holiday to honor the end of World War I, which officially took place on November 11, 1918 at 11:11am. On November 11, 1921 at 11:11 the USA, France and England each buried an unknown soldier in honor of those who died in World War I. In June 1954, <a href="https://en.wikipedia.org/wiki/Dwight_D._Eisenhower" target="_blank" rel="nofollow noreferrer">President Eisenhower</a> changed the name of Armistice Day to Veterans&rsquo; Day to honor all the USA Veterans.</p>
<p>Every year at 11.11 am on 11th November, a combined color guard representing all military services executes "Present Arms" at the tomb. The nation pays tribute to the veterans and keeps a moment of silence.</p>
<p>Veterans&rsquo; Day is held in honor of all those who served in the United States Armed Forces. This is different from Memorial Day which honors those who died while serving.<strong>&nbsp;</strong></p>
<h2><strong>Veterans&rsquo; Day Background</strong></h2>
<p>In 1921, an unknown World War I American soldier was buried in Arlington National Cemetery. Similarly, unknown soldiers had been buried in England at Westminster Abbey and at France at the Arc de Triomphe. All of these memorials took place on November 11th to commemorate the end of the "war to end all wars." In 1926, Congress resolved to officially call November 11th Armistice Day. Then in 1938, the day was named a national holiday. Soon afterward war broke out in Europe, and World War II began. Soon after the end of World War II, a veteran of that war named Raymond Weeks organized "National Veterans Day" with a parade and festivities to honor all veterans. He chose to hold this on Armistice Day. Thus began annual observances of a day to honor all veterans, not just the end of World War I. In 1954, Congress officially passed and President Dwight Eisenhower signed a bill proclaiming November 11 as Veterans&rsquo; Day.</p>
<p>Memorial Day and Veterans&rsquo; Day are both patriotic holidays honoring the military, but there is a significant difference between the two aside from when they land on the calendar. Memorial Day, which falls on the last Monday in May, honors the men and women who died while serving in the military. This solemn occasion is a time to reflect on these American patriots who made the ultimate sacrifice while protecting and defending the country they deeply loved. Veterans&rsquo; Day, observed every November 11, recognizes all who have served in the Armed Forces.</p>
<h2><strong>Veterans&rsquo; Day Celebrations </strong></h2>
<p>There are many parades and services throughout the country that honor veterans. The National Ceremony is held each year at Arlington National Cemetery where the president gives a speech and veterans are honored. Most major cities such as New York City, San Diego, and Dallas have a Veterans&rsquo; Day parade. At many events, such as church services and football games, veterans will be asked to stand and then the crowd will honor them with applause.</p>
<p>Many people fly a US flag on this day to show their patriotism and support for the armed services. At 11am a moment of silence is observed to remember those who served. If you see a veteran or soldier on Veterans&rsquo; Day, be sure to thank them personally for their service to our country.</p>
<h2><strong>Veterans&rsquo; Day Customs and Traditions</strong></h2>
<p>Veterans Day is one of ten federal holidays recognized nationwide by the United States Government. All non-essential federal government offices are closed on Veterans&rsquo; Day, and all federal employees are paid even if they receive the day off. Many private-sector employees will also receive paid time off or special holiday pay on Veterans&rsquo; Day. Veterans&rsquo; Day is a remembrance of all U.S. military veterans &ndash; past and present. It is celebrated every November 11th, and has been a federal holiday since 1926.</p>
<h2><strong>Veterans&rsquo; Day Facts</strong></h2>
<ul>
<li>One year after the end of World War I, US President Woodrow Wilson instituted Armistice Day. Armistice Day was introduced to remember those who died during the war. It falls on the anniversary of when the Armistice with Germany went into effect &ndash; the 11th hour of the 11th day of the 11th month. This is considered the first Veterans day, though it went by a different name.</li>
<li>In 1938, 20 years after the end of World War I and 19 years after the first Armistice Day, the United States Congress made Armistice Day a legal holiday. The federal holiday is celebrated every November 11. US Post Offices are closed on this day, as well as some parts of the government.</li>
<li>A veteran of World War II, Raymond Weeks, wanted to expand the celebration of Armistice Day to include all veterans, not just the ones who served and died in the First World War. In 1954, President Dwight D. Eisenhower signed a congressional bill that expanded the scope of Armistice Day. A couple of days after the president signed the bill, Congress changed the name of Armistice Day to Veterans Day.</li>
<li>The National Veterans Award was first awarded in 1954 in Birmingham, Alabama, home of Raymond Weeks. According to Veterans Day facts, this award is given annually. The first person to receive the award was Congressman Ed Rees of Kansas, who wrote the legislation for, and championed the expansion of, Armistice Day to Veterans Day.</li>
<li>From 1971 to 1977, Veterans Day was celebrated on the fourth Monday in October as part of the Uniform Monday Holiday Act. In 1978, the holiday took back its rightful date on November 11 and continues to be celebrated annually on that day. However, if Veterans Day falls on a Saturday or Sunday, businesses and government organizations that celebrate may be closed on the Friday or Monday before or after the holiday.</li>
<li>Veterans Day facts show that on Memorial Day, the United States remembers those who gave their lives in battle. In contrast, Veterans Day celebrates the lives of soldiers, living or dead, who have fought for their country.</li>
<li>Australia and Canada both celebrate Remembrance Day on November 11 to commemorate the veterans of World Wars I and II. The United Kingdom celebrates Remembrance Day on the Sunday closest to November 11. Some countries, including France, still celebrate Armistice Day to mark the end of World War I.</li>
<li>Many calendars and ads insert an apostrophe into Veterans Day, spelling it either Veteran&rsquo;s Day or Veterans&rsquo; Day. Using an apostrophe implicates possession. The United States government decreed the proper spelling does not use an apostrophe, making Veterans an attributive noun that modifies the noun Day.</li>
<li>When President Eisenhower signed the Veterans Day Bill, he also appointed the Veterans Affairs Chairman to a newly created position, the Chairman of the Veterans Day National Committee. Now, every Veterans Affairs Chairman is also the Chairman of the Veterans Day National Committee.</li>
<li>Veterans Day facts indicate Arlington National Cemetery is a national burial ground for those who have served their country. Every Veterans Day at 11 AM, a ceremony is held around the Tomb of the Unknowns to mark the sacrifices of veterans everywhere.</li>
<li>Raymond Weeks championed the creation of a national Veterans&rsquo; Day that included more than just World War I veterans. He even petitioned and convinced Eisenhower before he became president. For his tireless action in honor of veterans, President Reagan gave Weeks the Presidential Citizenship Medal in 1982.</li>
<li>While Raymond Weeks worked towards making Veterans Day a national holiday, he instituted a parade and celebration in his hometown of Birmingham, Alabama. Weeks led the annual parade from 1947 &ndash; the first parade &ndash; until his death in 1985. Veterans Day facts show the parade still continues as the city of Birmingham carries on his legacy.</li>
<li>Every year the US Department of Veterans&rsquo; Affairs runs an official Veterans Day ceremony. This ceremony is generally held at Arlington National Cemetery and features a speech from a high-ranking government official. President Bill Clinton spoke at the ceremony every year he was in office. He has given the most Veterans Day speeches and is the only President to speak every year of his presidency.</li>
<li>New York City has held an annual Veterans Day parade since 1929. With around 25,000 participants each year, it is the nation&rsquo;s largest Veterans Day parade. At 10 AM, an hour before the official start of the parade, a wreath is laid in Madison Square Park at the Eternal Light Flagstaff. At 11 AM the parade commences with marchers, floats, and marching bands.</li>
<li>Part of the annual New York City celebration, the Eternal Light Flagstaff is a sculpture created by Paul Wayland Bartlett to commemorate the homecoming of the US Army and Navy after World War I. It was dedicated on Veterans Day in 1923.</li>
</ul>
<h2><strong>Veterans&rsquo; Day Symbols</strong></h2>
<p>The Official Symbol of Veterans Day is the Poppy</p>
<p>In 1918, a woman in Georgia named Moina Belle Michael read a John McCrae poem called "In Flanders Fields", and she was inspired her to wear red poppies. Now, Veterans all over the country can be found selling poppies on Veterans Day. The poem Michael read includes the line, "In Flanders fields the poppies blow / Between the crosses row on row."</p>
';
?>
